import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { projects } from "../../../db/schema";

export const metadata: Metadata = { title: "Status projektu", robots: { index: false, follow: false }, openGraph: { images: [] }, twitter: { images: [] } };
const stages=["Planowanie","Treści","Projekt graficzny","Wdrożenie","Testy","Opublikowany","Opieka"];

export default async function ClientStatus({params}:{params:Promise<{code:string}>}){const {code}=await params;const [project]=await getDb().select().from(projects).where(eq(projects.publicCode,decodeURIComponent(code).toUpperCase())).limit(1);if(!project)notFound();const stageIndex=Math.max(0,stages.indexOf(project.status));
return <main className="client-status"><nav className="nav shell"><Link className="brand" href="/"><img className="brand-logo" src="/logo.png" alt=""/><span>ZIELONA MARKA</span></Link><span>Strefa klienta</span></nav><div className="client-status-shell"><header><span className="section-no">PROJEKT {project.publicCode}</span><h1>{project.title}</h1><p>{project.clientCompany||project.clientName}</p></header><section className="client-kpis"><article><span>Aktualny etap</span><b>{project.status}</b></article><article><span>Postęp</span><b>{project.progress}%</b></article><article><span>Planowany termin</span><b>{project.deadline?new Date(project.deadline).toLocaleDateString("pl-PL"):"Do ustalenia"}</b></article><article><span>Umowa</span><b>{project.contractStatus}</b></article></section><section className="status-track" aria-label="Etapy projektu">{stages.slice(0,6).map((stage,index)=><div className={index<=stageIndex?"done":""} key={stage}><i>{index<stageIndex?"✓":String(index+1).padStart(2,"0")}</i><span>{stage}</span></div>)}</section><section className="client-status-grid"><article><span className="section-no">NASTĘPNY KROK</span><h2>{project.nextStep}</h2><p>{project.clientNote||"Gdy pojawi się informacja potrzebna od Ciebie, zobaczysz ją właśnie tutaj."}</p></article><article><span className="section-no">ZAKRES PROJEKTU</span><p>{project.scope||project.description||"Zakres jest obecnie doprecyzowywany."}</p></article></section><section className="client-documents"><div><span className="section-no">DOKUMENTY</span><h2>Umowa projektu</h2><p>Otwórz wzór umowy, sprawdź dane, zapisz jako PDF lub wydrukuj. Podpisany skan możesz odesłać na e-mail.</p></div><div><Link className="button" href={`/status/${project.publicCode}/umowa`}>Otwórz umowę <span>↗</span></Link><a className="text-link" href="mailto:lukasz.staniewicz@gmail.com?subject=Podpisana%20umowa%20Zielona%20Marka">Odeślij podpisaną umowę e-mailem</a></div></section><footer><p>Masz pytanie? Napisz: <a href="mailto:lukasz.staniewicz@gmail.com">lukasz.staniewicz@gmail.com</a></p></footer></div></main>}
