import type { Metadata } from 'next';
import BistroMenu from './BistroMenu';
import './bistro-demo.css';
export const metadata: Metadata={title:'Bistro Forma | sezonowe menu, demonstracja',description:'Poglądowa strona restauracji z menu i wyborem dań.',robots:{index:false,follow:false},openGraph:{images:[]},twitter:{images:[]}};
export default function BistroWebsiteDemo(){return <main className="bf-site">
 <div className="bf-demo">DEMONSTRACJA ZIELONEJ MARKI <a href="/realizacje">Wróć do portfolio ↗</a></div>
 <nav className="bf-nav" aria-label="Bistro Forma"><a className="bf-brand" href="#start">bistro<span>FORMA</span></a><div><a href="#historia">O nas</a><a href="#menu">Menu</a><a href="#klimat">Klimat</a><a href="#kontakt">Kontakt</a></div><a className="bf-cta" href="#menu">Wybierz coś dobrego ↗</a></nav>
 <header className="bf-hero" id="start"><img src="/concept-bistro.jpg" alt="Ciepłe wnętrze koncepcyjnego bistro"/><div><span>SEZONOWO. LOKALNIE. PRZY JEDNYM STOLE.</span><h1>Dobre jedzenie.<br/><em>Dobry powód,<br/>żeby się spotkać.</em></h1><p>Krótka karta, pełne smaki i miejsce na jeszcze jedną rozmowę.</p><a className="bf-cta" href="#menu">Zajrzyj do menu ↓</a></div><b className="bf-round">ŚWIEŻO<br/>KAŻDEGO<br/>DNIA ✳</b></header>
 <section className="bf-info" aria-label="Informacje o lokalu"><div><small>KUCHNIA</small><b>Sezonowa i swobodna</b></div><div><small>GODZINY PRZYKŁADOWE</small><b>12:00–22:00</b></div><div><small>NA MIEJSCU I NA WYNOS</small><b>Tak, jak lubisz</b></div><a href="#menu">Odkryj kartę ↗</a></section>
 <section className="bf-story bf-wrap" id="historia"><span className="bf-kicker">ZAPRASZAMY DO STOŁU</span><h2>Smak zostaje.<br/><em>Reszta może poczekać.</em></h2><p>Pieczemy, mieszamy, doprawiamy. Z prostych składników robimy dania, po które chce się wracać. Wpadnij na szybki lunch albo zostań z nami na cały wieczór.</p></section>
 <section className="bf-menu" id="menu"><div className="bf-wrap"><header><span className="bf-kicker">CO DOBREGO?</span><h2>Mała karta.<br/>Wielka ochota.</h2><p>Wybierz kategorię i skomponuj przykładowy posiłek. Ceny są poglądowe.</p></header><div className="bf-specials"><div><b>Lunch w dobrym rytmie</b><span>Krótka przerwa, pełny talerz.</span></div><div><b>Zostaw miejsce na deser</b><span>Sernik, kawa i jeszcze chwila.</span></div><div><b>Przy jednym stole</b><span>Dobry smak najlepiej dzielić.</span></div></div><BistroMenu/></div></section>
 <section className="bf-atmosphere" id="klimat"><img src="/concept-bistro.jpg" alt="Klimat Bistro Forma" loading="lazy"/><div><span className="bf-kicker">NIE TYLKO NA WIELKIE OKAZJE</span><h2>Twój ulubiony<br/>zwykły wieczór.</h2><p>Ciepłe światło. Dobra kuchnia. Swobodna rozmowa.</p><a href="#menu">Co dziś wybierasz? ↗</a></div></section>
 <footer className="bf-footer" id="kontakt"><div className="bf-brand">bistro<span>FORMA</span></div><p>Autorska marka demonstracyjna.<br/>Ta strona nie przyjmuje prawdziwych zamówień.</p><div><a href="/demo/bistro">Zobacz demonstrację zaplecza ↗</a><a href="/kontakt">Chcę stronę dla restauracji ↗</a><a href="/realizacje">Wróć do portfolio</a></div></footer>
 </main>}
