import type { Metadata } from "next";
import Link from "../SafeLink";
import { SiteHeader, SiteFooter } from "../SiteChrome";

export const metadata: Metadata = { title: "Opieka i rozwój strony", description: "Opcjonalna opieka nad stroną, aktualizacje, kontrola formularzy i rozwój funkcji dopasowany do firmy.", alternates: { canonical: "/opieka-nad-strona" } };

export default function CarePage() {
  return <><SiteHeader /><main className="zm-public">
    <section className="page-hero shell"><span className="eyebrow">PO PUBLIKACJI</span><h1>Strona gotowa na <em>kolejny krok.</em></h1><p>Po przekazaniu strony otrzymujesz 14 dni podstawowego wsparcia startowego. Późniejsza opieka jest opcjonalna. Możemy zadbać o bieżące działanie albo rozbudować stronę, kiedy potrzebuje tego Twoja firma.</p><Link className="button" href="/kontakt">Ustalmy zakres opieki ↗</Link></section>
    <section className="section shell" id="opieka"><div className="section-head"><div><span className="section-no">OPIEKA ABONAMENTOWA</span><h2>Spokojne działanie na co dzień.</h2></div><p>249–490 zł netto / miesiąc. Zakres, częstotliwość kontroli, limit zmian i czas reakcji ustalamy przed rozpoczęciem współpracy.</p></div><div className="extra-grid"><article><h3>Kontrola działania</h3><p>Sprawdzenie dostępności strony, formularzy i kluczowych ścieżek kontaktu. Dzięki temu łatwiej wykryć problem, zanim zgłosi go klient.</p></article><article><h3>Aktualizacje i kopie</h3><p>Uzgodnione aktualizacje oraz kontrola kopii bezpieczeństwa odpowiednia do technologii strony. Hosting i usługi zewnętrzne rozliczamy osobno.</p></article><article><h3>Drobne zmiany</h3><p>Aktualizacja godzin, danych kontaktowych, tekstów lub zdjęć w ustalonym limicie. Nowe podstrony i funkcje wyceniamy oddzielnie.</p></article></div></section>
    <section className="section shell" id="rozwoj"><div className="section-head"><div><span className="section-no">ROZWÓJ W TWOIM TEMPIE</span><h2>Nowe możliwości, gdy mają sens.</h2></div><p>Najpierw ustalamy cel i zakres. Każde rozszerzenie otrzymuje osobną wycenę i termin, bez obowiązku abonamentu.</p></div><div className="extra-grid"><article><h3>Lepsza oferta i widoczność</h3><p>Nowa usługa, podstrona, uzupełnienie treści i uporządkowanie informacji pomagających klientowi wybrać firmę.</p><Link href="/modernizacja-strony">Modernizacja strony ↗</Link></article><article><h3>Sprzedaż i rezerwacje</h3><p>Mały sklep, płatności, vouchery lub połączenie z systemem rezerwacji dopasowanym do Twojej działalności.</p><Link href="/oferta#mini-sklep">Sklepy i płatności ↗</Link></article><article><h3>Mniej pracy ręcznej</h3><p>Formularze, przypomnienia, integracje i mały CRM, które porządkują obsługę zapytań oraz zleceń.</p><Link href="/usprawnienia-firmy#automatyzacje">Zobacz usprawnienia ↗</Link></article></div></section>
  </main><SiteFooter /></>;
}
