import QualityBadge from "../QualityBadge";
import type { Metadata } from "next";
import Image from "next/image";
import Script from "next/script";
import Link from "../SafeLink";
import { QuickWhatsApp, SiteFooter, SiteHeader } from "../SiteChrome";
import { processSteps } from "../site-data";

export const metadata: Metadata = {
  title: "Jak wygląda współpraca nad stroną",
  description: "Jasny proces od briefu do publikacji strony: projekt, poprawki, kontrola jakości, przygotowanie do Google i opieka.",
  alternates: { canonical: "/jak-pracuje" },
};

const faq = [
  ["Czy muszę od razu wiedzieć, czego potrzebuje moja firma?", "Nie. Wystarczy opisać, co dziś zabiera czas, gdzie klientom trudno się skontaktować albo jakie informacje giną po drodze. Na tej podstawie wspólnie ustalimy, czy pierwszym krokiem ma być strona, formularz, rezerwacja, mały CRM czy tylko poprawa obecnego rozwiązania."],
  ["Czy musimy spotykać się osobiście?", "Nie. Współpraca może odbywać się przez Google Meet, telefon, e-mail i WhatsApp. Działam lokalnie, ale realizuję projekty zdalnie dla firm z całej Polski."],
  ["Czy mogę samodzielnie edytować treść?", "Tak, jeśli projekt tego wymaga. Przed startem wybieramy prosty sposób aktualizacji, np. WordPress, albo ustalamy zakres opieki nad stroną."],
  ["Ile propozycji projektu otrzymam?", "Pracujemy na jednym, dopasowanym kierunku projektu. Dzięki temu zamiast wybierać przypadkowy szablon, poprawiamy rozwiązanie przygotowane dla Twojej firmy."],
  ["Ile poprawek obejmuje projekt?", "W uzgodnionym zakresie są dwie rundy poprawek. Nowe funkcje, kolejne podstrony lub zmiana kierunku po akceptacji są wyceniane osobno przed rozpoczęciem."],
  ["Czy strona będzie widoczna w Google?", "Przygotowuję techniczne podstawy: strukturę, opisy, wersję mobilną, szybkość i możliwość zgłoszenia strony do Google. Pomagam też przygotować wizytówkę Google dla firmy lokalnej. Nie obiecuję konkretnej pozycji, ponieważ zależy ona też od konkurencji i dalszych działań."],
  ["Ile kosztuje strona internetowa dla małej firmy?", "Kompletna, jedna przewijana strona ZM Start zaczyna się od 1 449 zł. Końcowa cena zależy od materiałów, liczby podstron, treści, integracji i funkcji, dlatego przed startem zawsze potwierdzamy zakres."],
  ["Czy robisz strony dla firm lokalnych?", "Tak. Strona może pokazać obszar działania, najważniejsze usługi, telefon, WhatsApp, mapę oraz prostą drogę do zapytania. Współpracuję także z firmami z całej Polski."],
  ["Czy mogę mieć stronę bez WordPressa?", "Tak. WordPress dobieramy tylko wtedy, gdy firma chce samodzielnie często zmieniać treści. Prostsza, szybsza strona może działać bez panelu WordPress, a aktualizacje możemy wykonywać w ramach opieki."],
  ["Czy stronę można później rozbudować o mały CRM?", "Tak. Mały CRM to proste zaplecze dla firmy: porządek w zapytaniach, statusach zleceń, klientach i najważniejszych liczbach. Zaczynamy od funkcji, które naprawdę oszczędzają czas, zamiast budować rozbudowany system na zapas."],
  ["Co oznacza kontrola jakości (QA)?", "QA to skrót od angielskiego Quality Assurance, czyli kontroli jakości. Sprawdzam telefon, komputer, formularze, linki, szybkość, podstawową dostępność oraz pełną ścieżkę klienta."],
  ["Co dzieje się po publikacji?", "Przekazuję uzgodnione dostępy, instrukcję i 14 dni podstawowego wsparcia startowego. Dalsza opieka jest opcjonalna."],
  ["Jak wygląda płatność 30/70?", "30% zaliczki po akceptacji zakresu i umowy rezerwuje termin i rozpoczyna pracę. Pozostałe 70% jest płatne po akceptacji gotowej wersji i kontroli jakości (QA), przed publikacją na domenie lub serwerze klienta."],
  ["Kto jest właścicielem domeny i strony?", "Domena, konto hostingu, konto płatności i inne konta powinny należeć do klienta. Po rozliczeniu klient otrzymuje uzgodniony efekt pracy oraz dostępy."],
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faq.map(([name, text]) => ({
    "@type": "Question",
    name,
    acceptedAnswer: { "@type": "Answer", text },
  })),
};

export default function HowWeWorkPage() {
  return <><Script id="jak-pracuje-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><SiteHeader /><main className="zm-public">
    <section className="page-hero shell"><span className="eyebrow"><i />JAK PRACUJĘ</span><h1>Jasne decyzje od pierwszej rozmowy <em>do działającej strony.</em></h1><p>Nie musisz prowadzić projektu technicznie. Wiesz, czego potrzebuję od Ciebie, co robię na danym etapie i kiedy podejmujemy decyzję.</p><Link className="button" href="/kontakt">Zacznij od briefu <span>↗</span></Link></section>
    <section className="section about-intro"><div className="shell about-intro-grid"><div><span className="section-no">POZNAJMY SIĘ</span><h2>Strona ma ułatwiać kontakt, a nie tylko dobrze wyglądać.</h2></div><div><p>Prowadzę działalność od 2011 roku, a od 2014 roku rozwijam strony i narzędzia w kodzie. Pomagam firmom uporządkować pierwsze wrażenie, zebrać konkretne zapytania i spokojniej prowadzić klienta od wejścia na stronę do kontaktu.</p><p>Tworzę strony, formularze, integracje i proste zaplecza dla firm, które chcą działać czytelniej. Zanim coś opublikuję, sprawdzam pełną ścieżkę klienta na telefonie i komputerze, w tym formularz, telefon, e-mail oraz WhatsApp.</p></div></div><div className="shell about-proof-list"><article><span>01</span><h3>Najpierw cel</h3><p>Rozmowa zaczyna się od sytuacji firmy i problemu klienta, a nie od listy technologii.</p></article><article><span>02</span><h3>Potem kontrola</h3><p>Przed publikacją sprawdzam widoki, linki, formularze i podstawowe ścieżki kontaktu.</p></article><article><span>03</span><h3>Po starcie pomiar</h3><p>Za zgodą odwiedzających konfiguruję GA4, aby było widać źródła wejść i działania prowadzące do kontaktu.</p></article></div></section>
    <section className="section shell"><div className="section-head"><div><span className="section-no">PROCES</span><h2>Od pomysłu do publikacji.</h2></div><p>Mała, podstawowa strona: od 72 godzin do 14 dni od otrzymania kompletu materiałów i ustalenia zakresu. Rozbudowane strony, sklepy i systemy mają terminy ustalane osobno.</p></div><div className="timeline">{processSteps.map(([number, title, description]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="section meeting-section"><div className="shell meeting-grid"><div><span className="section-no">SPOTKANIE ONLINE I PRZYGOTOWANIE PROJEKTU</span><h2>Jedna rozmowa może uporządkować cały kierunek.</h2><p>Możemy spotkać się przez Google Meet. Na ekranie pokazuję pierwszy układ strony, najważniejsze kroki klienta i elementy, które mają odciążyć Twoją firmę.</p><p>Po spotkaniu otrzymujesz prosty plan: co przygotowujemy, co jest pierwszym etapem i jaki będzie następny krok.</p><Link className="button" href="/kontakt">Umów krótką rozmowę <span>↗</span></Link></div><figure className="meeting-visual"><Image src="/lukasz-zielona-marka-jak-pracuje-20260908.webp" width={1672} height={941} alt="Łukasz pracujący nad stroną internetową i kodem" unoptimized /><figcaption>Projektowanie strony, sprawdzanie widoku i praca nad kodem.</figcaption></figure></div></section>
    <section className="section qa-section"><div className="shell qa-grid"><div><span className="section-no">KONTROLA JAKOŚCI / QA</span><h2>Strona jest testowana, zanim zacznie pracować na Twoją firmę.</h2><p className="spaced-copy">Kontrola jakości (<b>QA</b>, ang. <i>Quality Assurance</i>) oznacza ostatnie sprawdzenie strony przed publikacją. Na koniec otrzymujesz proste podsumowanie: co zostało sprawdzone i&nbsp;co jest gotowe do startu.</p><QualityBadge /></div><div><ul className="check-list"><li>telefon, tablet i komputer</li><li>formularze, e-mail, numer telefonu i WhatsApp</li><li>linki, przekierowania i podstawowe błędy</li><li>szybkość oraz stabilność</li><li>przygotowanie do Google i mapa strony</li><li>podstawowa dostępność oraz czytelność</li></ul><p><b>Lighthouse</b> to test Google sprawdzający m.in. szybkość, dostępność i techniczną jakość strony. Jest narzędziem kontroli, a nie gwarancją pozycji w wyszukiwarce.</p><Link className="text-link" href="/raport-qa">Zobacz przykładowy raport kontroli jakości <span>↗</span></Link></div></div></section>
    <section className="section technology-section"><div className="shell"><div className="section-head"><div><span className="section-no">NARZĘDZIA DOBIERAM DO CELU</span><h2>Klient nie musi znać technologii, żeby dostać dobre rozwiązanie.</h2></div><p>Najpierw ustalamy, co ma zmienić się w&nbsp;firmie. Dopiero potem wybieram sposób wykonania strony, formularza, automatyzacji lub prostego zaplecza.</p></div><div className="technology-grid"><article><span>01 / FRONT-END</span><h3>To, co widzi klient</h3><p><b>HTML, CSS, JavaScript, TypeScript i&nbsp;React</b> odpowiadają za czytelną, szybką stronę, wygodny formularz i&nbsp;działanie na telefonie.</p></article><article><span>02 / BACK-END</span><h3>To, co działa w&nbsp;tle</h3><p><b>NestJS, Java, PHP, API i&nbsp;webhooki</b> pozwalają przekazywać zgłoszenia, łączyć usługi i&nbsp;uruchamiać logikę po wysłaniu formularza.</p></article><article><span>03 / REZERWACJE</span><h3>Wizyta bez chaosu</h3><p><b>Booksy, kalendarz i&nbsp;formularz terminu</b> pomagają prowadzić klienta do rezerwacji bez budowania drugiego systemu na siłę.</p></article><article><span>04 / PŁATNOŚCI</span><h3>Bezpieczne zakupy</h3><p><b>WooCommerce, Shopify, Przelewy24, Tpay i&nbsp;Stripe</b> pozwalają przyjąć płatność za produkt, voucher lub prostą usługę. Konto u&nbsp;operatora zawsze należy do klienta.</p></article><article><span>05 / AUTOMATYZACJE</span><h3>Mniej pracy ręcznej</h3><p><b>Python, n8n, Make i&nbsp;Power Automate</b> pomagają przekazywać dane, wysyłać przypomnienia i&nbsp;aktualizować statusy bez przepisywania informacji.</p></article><article><span>06 / DANE</span><h3>Porządek i&nbsp;raporty</h3><p><b>Zaawansowany Excel, Google Sheets, Looker Studio i&nbsp;Power BI</b> pokazują terminy, koszty i&nbsp;najważniejsze liczby firmy na jednym ekranie.</p></article><article><span>07 / MAŁY CRM</span><h3>Zapytania nie giną</h3><p><b>SQL, Cloudflare D1, Airtable i&nbsp;bezpieczne API</b> porządkują klientów, zlecenia, statusy i&nbsp;następne działania w&nbsp;jednym miejscu.</p></article><article><span>08 / PANEL KLIENTA</span><h3>Mniej pytań o&nbsp;status</h3><p><b>Widok mobilny, bezpieczny kod dostępu i&nbsp;PWA</b> pozwalają klientowi sprawdzić etap, termin oraz dokumenty bez kolejnego telefonu.</p></article><article><span>09 / WORDPRESS</span><h3>Edycja bez dotykania kodu</h3><p><b>WordPress, Gutenberg, motyw blokowy, PHP, MySQL, pola własne i&nbsp;REST API</b> pozwalają samodzielnie edytować stronę, a&nbsp;jednocześnie tworzyć indywidualne szablony, realizacje, formularze oraz integracje.</p></article><article><span>10 / KONTROLA</span><h3>Gotowe do startu</h3><p><b>Kontrola jakości (QA, ang. Quality Assurance), Lighthouse, Google Search Console i&nbsp;GA4</b> pomagają sprawdzić stronę oraz zobaczyć, skąd przychodzą zapytania.</p></article></div></div></section>
    <section className="section shell technical-checks"><div className="section-head"><div><span className="section-no">CO SPRAWDZAM PRZED PUBLIKACJĄ</span><h2>Techniczne sprawy bez technicznego języka.</h2></div><p>To elementy, które pomagają stronie być czytelną dla ludzi, Google i urządzeń mobilnych.</p></div><div className="technical-check-grid"><article><span>01</span><h3>Informacje dla Google</h3><p>Każda ważna podstrona dostaje własny tytuł, opis i właściwy adres. Dzięki temu wyszukiwarka lepiej rozumie, czego dotyczy strona.</p></article><article><span>02</span><h3>Jedna właściwa wersja adresu</h3><p>Ustawiam główny adres strony, aby nie powstawały kopie pod różnymi wariantami domeny.</p></article><article><span>03</span><h3>Obrazek przy udostępnianiu</h3><p>Przygotowuję grafikę i opis, które pokazują się po wklejeniu linku na Facebooku, w Messengerze czy SMS-ie.</p></article><article><span>04</span><h3>Mapa strony i kontrola dostępu</h3><p>Strona otrzymuje mapę dla wyszukiwarek. Prywatne zaplecze i wersje demonstracyjne są oznaczone tak, aby nie trafiały do wyników Google.</p></article></div></section>
    <section className="section shell seo-grid"><div><span className="section-no">GOTOWA DO DALSZEGO SEO</span><h2>Po starcie nie trzeba naprawiać podstaw.</h2></div><div><p>Strona otrzymuje logiczną strukturę, poprawne adresy, tytuły i opisy, mapę strony, wersję mobilną, szybkie działanie i możliwość podłączenia narzędzi Google.</p><p>Widoczność w Google rozwija się później przez treści, lokalną wiarygodność, opinie i dalsze działania. Uczciwie nie gwarantuję konkretnej pozycji.</p></div></section>
    <section className="section rules-section"><div className="shell rules-grid"><article><span>30%</span><h3>Zaliczka na start</h3><p>Po akceptacji zakresu i umowy rezerwuję termin oraz rozpoczynam pracę.</p></article><article><span>70%</span><h3>Przed publikacją</h3><p>Po odbiorze gotowej wersji i kontroli jakości (QA), przed publikacją na serwerze klienta.</p></article><article><span>02</span><h3>Dwie rundy poprawek</h3><p>Uwagi zbieramy i wprowadzamy w jasno określonym zakresie.</p></article><article><span>14</span><h3>Dni wsparcia startowego</h3><p>Po publikacji pomagam spokojnie przejść przez pierwsze dni działania strony.</p></article></div></section>
    <section className="section shell faq-page"><div className="section-head"><div><span className="section-no">FAQ</span><h2>Najważniejsze odpowiedzi przed startem.</h2></div><p>Krótko, konkretnie i bez technicznego żargonu.</p></div><div className="faq-list">{faq.map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}<i>+</i></summary><p>{answer}</p></details>)}</div></section>
  </main><QuickWhatsApp /><SiteFooter /></>;
}




