import type { Metadata } from "next";
import Link from "../SafeLink";
import { QuickWhatsApp, SiteFooter, SiteHeader } from "../SiteChrome";

export const metadata: Metadata = { title: "Asystent zapytań dla lokalnej firmy usługowej", description: "Automatyczna obsługa powtarzalnych pytań, kwalifikacja zapytań i przekazanie kontaktu dla warsztatów, wykonawców, salonów beauty i lokalnych usług.", alternates: { canonical: "/asystent-zapytan" } };

export default function AssistantPage() {
  return <><SiteHeader /><main className="zm-public">
    <section className="page-hero shell"><span className="eyebrow"><i />ASYSTENT ZAPYTAŃ DLA FIRMY USŁUGOWEJ</span><h1>Odpowiada na powtarzalne pytania. <em>Trudniejsze przekazuje człowiekowi.</em></h1><p>Asystent działa na zatwierdzonej bazie wiedzy firmy, rozpoznaje potrzebę klienta, zbiera kontakt i przygotowuje podsumowanie rozmowy.</p><button className="button" type="button" data-open-demo-assistant>Wypróbuj demonstrację <span>↗</span></button></section>
    <section className="section shell assistant-capabilities"><div><span className="section-no">CO ROBI</span><h2>Pomaga przed pierwszym telefonem.</h2></div><div className="problem-grid"><article><span>01</span><h3>Odpowiada</h3><p>Godziny, obszar działania, zakres usług, przygotowanie do wizyty i inne zatwierdzone informacje.</p></article><article><span>02</span><h3>Kwalifikuje</h3><p>Pyta o usługę, lokalizację, termin, pojazd lub inne dane potrzebne w danej branży.</p></article><article><span>03</span><h3>Zapisuje kontakt</h3><p>Po zgodzie klienta przekazuje dane oraz podsumowanie do właściciela lub zespołu.</p></article><article><span>04</span><h3>Oddaje rozmowę</h3><p>Nie podaje wiążącej ceny i nie udaje człowieka. Zawsze umożliwia bezpośredni kontakt.</p></article></div></section>
    <section className="section assistant-rules"><div className="shell assistant-rules-grid"><div><span className="section-no">BEZPIECZNE ZASADY</span><h2>Automatyczny asystent nie może wymyślać warunków Twojej oferty.</h2><p>Przed wdrożeniem wspólnie zatwierdzamy pytania, odpowiedzi, ograniczenia oraz sposób przekazania rozmowy człowiekowi. W beauty asystent pomaga wybrać usługę i kieruje do wybranego przez salon sposobu rezerwacji.</p></div><ul className="check-list"><li>jasna informacja, że użytkownik rozmawia z automatycznym asystentem</li><li>odpowiedzi oparte na zatwierdzonych materiałach</li><li>brak wiążących wycen i obietnic terminów bez integracji</li><li>opcjonalnie Booksy, inny system albo formularz</li><li>kontakt telefoniczny i e-mail zawsze dostępne</li><li>testy scenariuszy przed uruchomieniem</li></ul></div></section>
    <section className="section shell assistant-costs"><div className="section-head"><div><span className="section-no">AUTOMATYZACJA JEST OPCJĄ, NIE OBOWIĄZKIEM</span><h2>Najpierw ustalamy, czy firma rzeczywiście go potrzebuje.</h2></div><p>Asystent może działać według zatwierdzonych scenariuszy. Zakres automatyzacji ustalamy dopiero po określeniu wiedzy, limitu kosztów oraz osoby odpowiedzialnej za treść.</p></div><div className="assistant-cost-grid"><article><b>01</b><h3>Własne konto firmy</h3><p>Firma zakłada konto dostawcy usługi, podłącza rozliczenie i ustala miesięczny limit. Prywatna subskrypcja rozmów nie jest do tego potrzebna.</p></article><article><b>02</b><h3>Obsługa techniczna</h3><p>Możemy utrzymywać techniczną stronę rozwiązania od 199 zł miesięcznie. Wykorzystanie usługi jest rozliczane zgodnie z faktycznym użyciem.</p></article><article><b>03</b><h3>Kontrola odpowiedzi</h3><p>Firma zatwierdza bazę wiedzy, ograniczenia i sposób przekazania rozmowy człowiekowi przed uruchomieniem.</p></article></div></section>
    <section className="section shell industry-package"><div><span className="section-no">PAKIET ZM BOT FAQ</span><h2>Asystent zapytań jako dodatek do strony</h2><p>Konfiguracja odpowiedzi, kwalifikacja potrzeby, zapis kontaktu, przekazanie zgłoszenia oraz testy.</p></div><div><strong>od 2 500 zł netto</strong><span>od 199 zł / mies. · zwykle 5 dni roboczych</span><small>Koszt miesięczny zależy od liczby rozmów i użytych narzędzi.</small><Link className="button" href="/kontakt">Zapytaj o asystenta <b>↗</b></Link></div></section>
  </main><QuickWhatsApp /><SiteFooter /></>;
}
