import Image from "next/image";
import Link from "./SafeLink";
import { Fragment } from "react";
import HomeContactForm from "./HomeContactForm";
import ForestHero from "./ForestHero";
import LivingPortal from "./LivingPortal";
import HomeStoryMotion from "./HomeStoryMotion";
import { QuickWhatsApp, SiteHeader, SiteFooter } from "./SiteChrome";
import "./home-v5.css";

function WebsiteVisual() {
  return <div className="zmh-visual"><p className="zmh-caption">Przykładowa strona dla branży beauty · demonstracja</p><div className="zmh-website zmh-glass"><div className="zmh-mini-nav"><b>✳ Natura Studio</b><span>O nas  Oferta  Kontakt</span></div><div className="zmh-site-interior"><span>CHWILA DLA SIEBIE</span><h3>Spokojniej.<br />Bliżej siebie.</h3><p>Pielęgnacja. Relaks. Naturalne piękno.</p><span className="zmh-sample-button">Poznaj zabiegi ↗</span></div></div></div>;
}

function FormVisual() {
  return <div className="zmh-visual zmh-form-visual"><div className="zmh-sample-form zmh-glass" aria-label="Ilustracja formularza dla firmy klienta"><p className="zmh-caption">PRZYKŁADOWY FORMULARZ USŁUGOWY</p><h3>Zapytaj o usługę</h3><div><span>Usługa</span><span>Wybierz usługę ⌄</span></div><div><span>Termin</span><span>Preferowany termin ▦</span></div><div><span>Opis</span><span>Opisz krótko sprawę…</span></div><span className="zmh-sample-button">Wyślij zapytanie →</span></div></div>;
}

function CommerceVisual() {
  return <div className="zmh-visual"><div className="zmh-commerce zmh-glass"><div className="zmh-voucher"><small>NATURA STUDIO</small><strong>Chwila<br />dla Ciebie.</strong><span>VOUCHER PODARUNKOWY</span></div><div className="zmh-commerce-copy"><p className="zmh-caption">PRZYKŁADOWY ZAKUP</p><h3>Pomysł<br />na prezent.</h3><p>Produkt → Koszyk → Płatność</p><small>Demonstracja zakupu vouchera.</small></div></div></div>;
}

function FlowVisual({ aftercare = false }: { aftercare?: boolean }) {
  const items = aftercare ? [["✓", "Zakończenie"], ["☏", "Kontakt po usłudze"], ["▦", "Kolejny krok"]] : [["✉", "Nowe zapytanie"], ["▤", "Wycena"], ["✓", "Realizacja"]];
  return <div className="zmh-visual"><div className="zmh-flow zmh-glass">{items.map(([icon, label], index) => <Fragment key={label}>{index > 0 && <i aria-hidden="true">→</i>}<div className={index === 0 ? "zmh-active zmh-flow-item" : "zmh-flow-item"}><span aria-hidden="true">{icon}</span><b>{label}</b></div></Fragment>)}</div><p className="zmh-caption zmh-bottom-caption">{aftercare ? "Przykład opieki nad klientem po realizacji." : "Przykładowy przebieg obsługi w systemie."}</p></div>;
}

export function OrganicHome() {
  return <main className="zm-v5">
    <a className="zmh-skip" href="#opowiesc">Przejdź do treści</a>
    <div className="zmh-forest" id="start">
      <div className="zmh-opening"><ForestHero /><SiteHeader />
      <section className="zmh-hero zmh-wrap" aria-labelledby="hero-title">
        <div className="zmh-hero-copy"><p className="zmh-eyebrow">STRONY WWW I SYSTEMY DLA FIRM</p><h1 id="hero-title">Masz dobrą firmę.<br /><em>Pokażmy ją z dobrej strony.</em></h1><p className="zmh-lead">Projektuję strony WWW dla firm usługowych. Pomagam też uporządkować zapytania, sprzedaż i obsługę klientów.</p><p className="zmh-service-line"><Link href="/oferta#branze">Formularze</Link> · <Link href="/oferta#mini-sklep">Sklepy i płatności</Link> · <Link href="/maly-crm-dla-firm">Systemy CRM</Link></p><p className="zmh-offer-proof">Dla <Link href="/strony-internetowe">lokalnych firm usługowych z Warszawy i okolic</Link> · od 1 449 zł netto · od 72 godzin do 14 dni*</p><div className="zmh-actions"><a className="zmh-pill" href="/kontakt">Porozmawiajmy o stronie <span aria-hidden="true">↗</span></a><Link className="zmh-quiet" href="/oferta">Zobacz ZM Start ↗</Link></div><p className="zmh-trust-note">Od pierwszej rozmowy pracujesz bezpośrednio ze mną.<br /> Gotową stronę oglądasz i zatwierdzasz przed publikacją.</p><p className="zmh-price-note">*Po otrzymaniu kompletu materiałów i ustaleniu zakresu.</p></div>
        <div className="zmh-hero-foot"><span className="zmh-aside-note">TWÓJ POMYSŁ.<br />WSPÓLNY KIERUNEK.</span><p>Dobry grunt<br />dla Twoich<br />pomysłów.</p></div>
      </section>
      </div><div className="zmh-scene-transition" aria-hidden="true"><span /></div><LivingPortal />
      <section className="zmh-free-start zmh-wrap" aria-labelledby="free-start-title">
        <header><div><p className="zmh-eyebrow">DOSTAŃ KONKRET, ZANIM COKOLWIEK ZAMÓWISZ</p><h2 id="free-start-title">Zobacz pierwszą szansę<br />dla swojej firmy. <em>Bezpłatnie.</em></h2></div><p>Wybierz jeden z dwóch materiałów. Dostaniesz konkretny następny krok, bez rozmowy o budżecie i bez zobowiązań.</p></header>
        <div className="zmh-free-start-grid">
          <article><span>01 / MASZ JUŻ STRONĘ</span><h3>Zobacz, co dziś odbiera Ci zapytania.</h3><p>Bezpłatnie wskażę jedną najważniejszą przeszkodę w wersji mobilnej, ofercie, kontakcie lub widoczności i pokażę zmianę, od której warto zacząć.</p><ul><li>wiesz, co poprawić najpierw</li><li>dostajesz konkretną rekomendację</li><li>nie wydajesz pieniędzy na przypadkowe zmiany</li></ul><div><Link className="zmh-pill" href="/modernizacja-strony#miniaudyt">Odbierz bezpłatny mini audyt <span>↗</span></Link><Link className="zmh-text-link" href="/demo/mini-audyt-zielona-marka">Zobacz przykład</Link><Link className="zmh-text-link" href="/poradnik/dlaczego-strona-firmy-nie-przynosi-zapytan">Przeczytaj poradnik</Link></div></article>
          <article className="recommended"><span>02 / POTRZEBUJESZ KIERUNKU</span><h3>Zobacz, jak prowadzić klienta do kontaktu.</h3><p>Bezpłatna Mapa Szans pokaże prostą drogę od wejścia na stronę, przez dobre pytania w formularzu, aż do sprawnej obsługi zapytania.</p><ul><li>widzisz, czego potrzebuje klient</li><li>wiesz, jakie informacje warto zebrać</li><li>dostajesz plan pierwszego procesu</li></ul><div><Link className="zmh-pill" href="/kontakt">Odbierz bezpłatną Mapę Szans <span>↗</span></Link><Link className="zmh-text-link" href="/demo/mapa-szans-zielona-marka">Zobacz przykład</Link></div></article>
        </div>
        <p className="zmh-free-start-note">Oba materiały są bezpłatne, przygotowane dla jednej firmy i służą wyborowi pierwszego kroku. Bez zobowiązania do dalszej współpracy. Mini audyt nie zastępuje pełnego audytu technicznego, a Mapa Szans kompletnej strategii.</p>
      </section>
      <section className="zmh-quick-brief zmh-wrap" id="krotki-brief" aria-labelledby="krotki-brief-title"><div className="zmh-quick-brief-copy"><p className="zmh-eyebrow">KRÓTKI BRIEF · OKOŁO 1 MINUTY</p><h2 id="krotki-brief-title">Masz już kierunek?<br /><em>Opisz go w kilku zdaniach.</em></h2><p>Nie musisz znać nazw funkcji ani gotowego rozwiązania. Napisz, czym zajmuje się firma i co chcesz ułatwić klientom lub sobie.</p><ul><li>odpowiadam najpóźniej w następnym dniu roboczym</li><li>bez zobowiązań i bez publikacji przed akceptacją</li></ul></div><div className="zmh-form-surface"><HomeContactForm /></div></section>
      <div className="zmh-cinema zmh-wrap">
        <div className="zmh-cinema-chapters">
          <section className="zmh-story" id="twoja-strona" aria-labelledby="strona-title"><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">01 / TWOJA STRONA</p><h2 id="strona-title">Strona, na której<br />łatwo Cię zrozumieć.</h2><p>Klient widzi, co oferujesz, dla kogo pracujesz i jak się z Tobą skontaktować. Układam treść, zdjęcia i nawigację tak, żeby tworzyły spójną opowieść o Twojej firmie.</p><p className="zmh-callout">Wybieramy to, czego potrzebujesz.<br />Od samej strony po połączone z nią narzędzia.</p><Link className="zmh-text-link" href="/oferta">Co obejmuje strona WWW ↗</Link><p className="zmh-callout">Zobacz przykłady dla: <Link href="/strony-dla-firm-uslugowych">firm usługowych</Link>, <Link href="/strony-dla-warsztatow">warsztatów i detailingu</Link> oraz <Link href="/strony-dla-beauty">branży beauty</Link>.</p></div><WebsiteVisual /></div></section>
          <section className="zmh-story" aria-labelledby="formularze-title"><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">02 / FORMULARZE</p><h2 id="formularze-title">Mniej dopytywania.<br />Więcej konkretów.</h2><p>Usługa, preferowany termin, kilka zdań o potrzebie. Dobrze dobrany formularz pomaga klientowi opisać sprawę, a Tobie przygotować rozmowę lub wycenę.</p><span className="zmh-aside-note">WIĘCEJ MIEJSCA<br />NA DOBRĄ ROZMOWĘ.</span></div><FormVisual /></div></section>
          <section className="zmh-story" aria-labelledby="sprzedaz-title"><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">03 / SKLEP I PŁATNOŚCI</p><h2 id="sprzedaz-title">Twoja oferta sięga<br />dalej niż wizyta.</h2><p>Kosmetyk polecony po zabiegu. Voucher dla kogoś bliskiego. Produkt, po który klient chce wrócić. Łączę stronę ze sklepem i płatnościami online, żeby można było kupić go także z domu.</p><Link className="zmh-text-link" href="/oferta#mini-sklep">Co obejmuje sklep z płatnościami ↗</Link></div><CommerceVisual /></div></section>
          <section className="zmh-story" aria-labelledby="crm-title"><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">04 / CRM I OBSŁUGA ZLECEŃ</p><h2 id="crm-title">Zapytanie przyszło.<br />Wiadomo, co dalej.</h2><p>Gdy ustalenia mają swoje miejsce, łatwiej zaplanować dzień. CRM to system, w którym łączę kontakty, wyceny, terminy i statusy zleceń. Wiesz, komu odpowiedzieć i co jest już zrobione.</p><Link className="zmh-text-link" href="/maly-crm-dla-firm">Zobacz, jak działa CRM ↗</Link></div><FlowVisual /></div></section>
          <section className="zmh-story zmh-relationships" aria-labelledby="relacje-title"><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">05 / KONTAKT PO USŁUDZE</p><h2 id="relacje-title">Dobre relacje<br />warto pielęgnować.</h2><p>Po wykonanej usłudze zostaje miejsce na pytanie, czy wszystko w porządku, prośbę o opinię albo przypomnienie o kolejnym terminie. Pomagam zaplanować taki kontakt i połączyć go z obsługą zleceń.</p></div><FlowVisual aftercare /></div></section>
        </div>
        <HomeStoryMotion />
      </div>
    </div>
    <div className="zmh-lower-forest">
      <section className="zmh-portfolio zmh-wrap" id="projekty" aria-labelledby="projekty-title"><div className="zmh-section-heading"><div><p className="zmh-eyebrow">PROJEKTY DEMONSTRACYJNE</p><h2 id="projekty-title">Zobacz, zanim zdecydujesz.</h2></div><div className="zmh-section-actions"><Link className="zmh-pill zmh-outline" href="/realizacje">Obejrzyj projekty ↗</Link><Link className="zmh-text-link" href="/praktyczne-narzedzia">Praktyczne narzędzia i aplikacje ↗</Link></div></div><p className="zmh-intro">Sprawdź, jak strona pomaga wybrać usługę, zaplanować wizytę albo znaleźć mieszkanie. Każdy przykład odpowiada na inną potrzebę.</p><div className="zmh-projects"><Link className="zmh-project zmh-glass" href="/demo/natura-strona"><Image src="/concept-natura.jpg" width={600} height={400} alt="Wnętrze demonstracyjnego studia wellness" unoptimized /><div><small>DEMONSTRACJA / BEAUTY</small><h3>Natura Studio</h3><p>Wybór zabiegu zaczyna się od jasnego opisu. Strona pokazuje usługi, ceny i drogę do umówienia wizyty.</p><span>Obejrzyj stronę studia ↗</span></div></Link><Link className="zmh-project zmh-glass zmh-bistro" href="/demo/bistro-strona"><Image src="/concept-bistro.jpg" width={600} height={400} alt="Wnętrze demonstracyjnej restauracji" unoptimized /><div><small>DEMONSTRACJA / GASTRONOMIA</small><h3>Bistro Forma</h3><p>Gość chce poczuć klimat miejsca i zaplanować wizytę. Strona łączy menu z informacją o rezerwacji.</p><span>Obejrzyj stronę restauracji ↗</span></div></Link></div><div className="zmh-more-projects"><Link href="/demo/dom-strona">Dom Dobry / mieszkania i dostępność ↗</Link><Link href="/realizacje/transportflow">TransportFlow / proces firmy transportowej ↗</Link></div><p className="zmh-caption">Opisy koncepcji: <Link href="/realizacje/natura-studio">Natura Studio</Link> · <Link href="/realizacje/bistro-forma">Bistro Forma</Link> · <Link href="/realizacje/dom-dobry">Dom Dobry</Link></p><p className="zmh-caption">Autorskie demonstracje możliwości. Nie są realizacjami dla klientów.</p></section>
      <section className="zmh-process zmh-wrap" id="proces" aria-labelledby="proces-title"><p className="zmh-chapter">WSPÓŁPRACA Z ZIELONĄ MARKĄ</p><h2 id="proces-title">Spokojny proces.<br />Wspólny kierunek.</h2><p>Mam na imię Łukasz. Tworzę strony i proste narzędzia, które ułatwiają kontakt z klientami i codzienną pracę firmy. Zaczynam od rozmowy o tym, czego potrzebujesz, a potem proponuję rozwiązanie i zakres prac. Rozmawiasz bezpośrednio ze mną i wiesz, co przygotowujemy oraz co będziesz zatwierdzać.</p><figure className="zmh-founder-photo"><Image src="/lukasz-zielona-marka-strona-glowna-20260908.webp" width={1000} height={563} alt="Łukasz podczas konsultacji projektu" unoptimized /><figcaption>Rozmawiasz bezpośrednio ze mną, od pomysłu po gotową stronę.</figcaption></figure><ol className="zmh-care-steps"><li><span>01</span><h3>Ustalamy zakres</h3><p>Wybieramy potrzebne funkcje i uzgadniamy zakres przed rozpoczęciem prac.</p></li><li><span>02</span><h3>Przygotowuję projekt</h3><p>Układam treści, wygląd i narzędzia. Ty oglądasz gotową propozycję.</p></li><li><span>03</span><h3>Ty zatwierdzasz</h3><p>Sprawdzam działanie strony. Publikacja następuje po Twojej akceptacji.</p></li></ol><Link className="zmh-text-link" href="/jak-pracuje">Przeczytaj zasady współpracy ↗</Link></section>
      <section className="zmh-story zmh-grow" aria-labelledby="rozwoj-title"><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">PO PUBLIKACJI / OPIEKA NAD STRONĄ</p><h2 id="rozwoj-title">Rozwój w rytmie<br />Twojej firmy.</h2><p>Nowa usługa, pomysł na sprzedaż, wygodniejszy sposób obsługi. Stronę można rozbudować, gdy pojawi się taka potrzeba. Dalszą opiekę i nowe funkcje ustalamy osobno, w zakresie dopasowanym do Twojej firmy.</p></div><div className="zmh-growth-words"><Link href="/opieka-nad-strona">Opieka ↗</Link><Link href="/usprawnienia-firmy#automatyzacje">Usprawnienia ↗</Link><Link href="/opieka-nad-strona#rozwoj">Rozwój ↗</Link></div></div></section>
      <section className="zmh-contact zmh-wrap" id="kontakt" aria-labelledby="kontakt-title"><LivingPortal contact /><div><p className="zmh-eyebrow">ZACZNIJMY OD ROZMOWY</p><h2 id="kontakt-title">Zróbmy miejsce<br />na <em>dobrą zmianę.</em></h2><p>Opowiedz, czym zajmuje się Twoja firma i co chcesz ułatwić sobie lub klientom. Wystarczy kilka zdań. Pomogę Ci wybrać kierunek i ustalić, od czego warto zacząć.</p><a className="zmh-pill" href="tel:+48450458466">Porozmawiajmy ↗</a><a className="zmh-phone" href="tel:+48450458466">+48 450 458 466</a><a className="zmh-text-link" href="#krotki-brief">Wolisz napisać? Wróć do krótkiego briefu ↑</a></div></section>
      <SiteFooter />
    </div>
    <QuickWhatsApp />
  </main>;
}
