import type { Metadata } from "next";
import { notFound } from "next/navigation";
import LocalCityPage, { type LocalCity } from "../../LocalCityPage";

const cities: Record<string, LocalCity> = {
  zabki: { name: "Ząbki", genitive: "Ząbek", locative: "Ząbkach", nearby: "Marki, Zielonka, Targówek i wschodnia Warszawa", lead: "Pomagam lokalnym usługodawcom jasno pokazać ofertę, zebrać dane potrzebne do wyceny i poprowadzić klienta od wyszukiwarki do kontaktu.", localNeed: "W Ząbkach klient często porównuje kilka firm z najbliższej okolicy. Strona powinna od razu pokazać, czym się zajmujesz, dokąd dojeżdżasz i jak szybko można rozpocząć rozmowę.", localContext: "Dla firmy działającej w Ząbkach oznacza to prostą wersję mobilną, jasny numer telefonu i sekcje, które nie każą klientowi szukać zakresu usługi po całej stronie.", fitTitle: "Najlepiej sprawdzi się u firmy, która wycenia usługę przed dojazdem.", fit: "W Ząbkach ten układ szczególnie pasuje do wykonawców, którzy potrzebują adresu, kilku zdjęć i krótkiego opisu zanim potwierdzą termin. Strona nie udaje kalkulatora ceny. Ma zebrać minimum informacji potrzebnych do decyzji: czy zlecenie jest w zakresie, czy trzeba dopytać i kiedy można oddzwonić.", contactTitle: "Pierwszy kontakt może od razu przygotować wycenę.", contactFlow: "Klient wybiera usługę, podaje lokalizację i dodaje materiały. Właściciel widzi komplet w jednym miejscu i może odpowiedzieć konkretnie: poprosić o dodatkowe dane, zaproponować oględziny albo wskazać pierwszy możliwy termin. Telefon zostaje dostępny dla pilnych spraw, ale nie musi obsługiwać każdego prostego pytania od zera.", exampleTitle: "Klient ze Skrajnej nie powinien zgadywać, czy do niego dojedziesz.", example: "Firma wyjazdowa może już w pierwszym formularzu zebrać ulicę, rodzaj pracy, zdjęcia i dogodny termin. Właściciel dostaje podstawy do oceny zlecenia, a klient nie czeka na serię pytań przez telefon.", checklist: ["obsługiwane części Ząbek i okolice", "minimalny zakres lub koszt dojazdu, jeśli obowiązuje", "jakie zdjęcia przygotować do wyceny", "realny czas odpowiedzi"], related: [["Zielonka", "zielonka"], ["Targówek", "targowek"], ["Warszawa", "warszawa"]] },
  zielonka: { name: "Zielonka", genitive: "Zielonki", locative: "Zielonce", nearby: "Marki, Ząbki, Kobyłka i Wołomin", lead: "Tworzę strony, formularze i proste zaplecza, które pomagają lokalnej firmie otrzymywać bardziej kompletne zapytania i sprawniej na nie odpowiadać.", localNeed: "Klient z Zielonki szuka wygodnego kontaktu i pewności, że firma rzeczywiście obsługuje jego rejon. Dobra strona łączy lokalną informację z konkretnym zakresem usługi.", localContext: "W Zielonce warto połączyć lokalny zasięg z konkretną specjalizacją. Dzięki temu klient widzi zarówno obszar działania, jak i powód, dla którego ma wybrać właśnie tę firmę.", fitTitle: "Dobre rozwiązanie dla firmy, która ma dwa typy kontaktu: pilny i planowany.", fit: "W Zielonce warto rozdzielić klienta, który potrzebuje szybkiego telefonu, od osoby planującej większe zlecenie. Jedna ścieżka może prowadzić do natychmiastowego kontaktu, druga do formularza z zakresem, zdjęciami i terminem. Dzięki temu strona nie zmusza wszystkich do tego samego sposobu rozmowy.", contactTitle: "Pilna sprawa i większa wycena nie powinny wyglądać tak samo.", contactFlow: "Dla szybkiej usługi klient dostaje widoczny numer i godziny kontaktu. Przy większym zakresie strona prosi o dane, które można spokojnie przejrzeć przed oddzwonieniem. Taki podział pomaga firmie odpowiadać w odpowiednim trybie, zamiast traktować każdą wiadomość jako równie pilną.", exampleTitle: "Jedna strona może rozdzielić szybką usługę od większej wyceny.", example: "Klient potrzebujący pilnej pomocy chce od razu zadzwonić. Przy większym zleceniu wygodniejszy będzie formularz ze zdjęciami i opisem. Strona powinna pokazać oba wejścia, zamiast zmuszać wszystkich do tej samej ścieżki.", checklist: ["numer do pilnych spraw", "formularz do większej wyceny", "obsługiwane usługi i wyłączenia", "Zielonka oraz rzeczywisty zasięg dojazdu"], related: [["Ząbki", "zabki"], ["Kobyłka", "kobylka"], ["Wołomin", "wolomin"]] },
  kobylka: { name: "Kobyłka", genitive: "Kobyłki", locative: "Kobyłce", nearby: "Zielonka, Wołomin, Marki i Radzymin", lead: "Projektuję strony internetowe dla firm usługowych, które chcą lepiej prezentować ofertę, kwalifikować zapytania i pilnować kolejnych kroków obsługi.", localNeed: "W Kobyłce wiele usług opiera się na dojeździe, terminie albo wcześniejszej wycenie. Strona może zebrać lokalizację, zakres i zdjęcia, zanim właściciel oddzwoni.", localContext: "Dla usług wyjazdowych z Kobyłki najwięcej zmienia formularz, który już na początku zbierze miejsce realizacji, zdjęcia i dogodny termin kontaktu.", fitTitle: "Najwięcej zyskują wykonawcy, którzy potrzebują ocenić zakres przed wizytą.", fit: "W Kobyłce ten model dobrze pasuje do montażu, serwisu i prac remontowych. Klient może od razu pokazać miejsce, opisać problem i zaznaczyć termin. Firma nie musi zaczynać od serii wiadomości z pytaniami o podstawy, a część zleceń można wstępnie zakwalifikować jeszcze przed rozmową.", contactTitle: "Zdjęcia i zakres stają się częścią zgłoszenia, nie dodatkiem po telefonie.", contactFlow: "Formularz może prowadzić krok po kroku: rodzaj pracy, lokalizacja, przybliżony zakres, zdjęcia i dostępność czasowa. Po stronie firmy zgłoszenie ma od razu kontekst. To skraca pierwszą rozmowę i pomaga rozróżnić drobną usługę od zlecenia wymagającego oględzin.", exampleTitle: "Zdjęcia i lokalizacja przed oddzwonieniem oszczędzają pusty dojazd.", example: "Przy naprawie, montażu lub remoncie sam numer telefonu często nie wystarcza. Formularz może poprosić o krótki opis, kilka zdjęć i adres. Dzięki temu pierwsza rozmowa zaczyna się od konkretu.", checklist: ["typ i zakres usługi", "możliwość dodania zdjęć", "adres realizacji", "preferowany termin kontaktu"], related: [["Zielonka", "zielonka"], ["Wołomin", "wolomin"], ["Radzymin", "radzymin"]] },
  wolomin: { name: "Wołomin", genitive: "Wołomina", locative: "Wołominie", nearby: "Kobyłka, Zielonka, Radzymin i okolice powiatu wołomińskiego", lead: "Buduję strony i niewielkie systemy dla firm, które chcą zamieniać lokalne wejścia z Google w uporządkowane rozmowy, wyceny i zlecenia.", localNeed: "Firma z Wołomina może obsługiwać całe miasto i sąsiednie gminy. Strona powinna wyjaśnić zasięg, pokazać specjalizację oraz ułatwić przekazanie informacji potrzebnych do wyceny.", localContext: "Przy obsłudze miasta i sąsiednich gmin dobrze działają osobne opisy usług oraz przejrzysta informacja o dojeździe, czasie odpowiedzi i sposobie wyceny.", fitTitle: "Układ dla firmy, która obsługuje nie tylko miasto, ale kilka sąsiednich gmin.", fit: "W Wołominie ważne jest rozdzielenie informacji o usłudze od zasad dojazdu. Klient powinien móc sprawdzić, czy jego lokalizacja jest w zasięgu, zanim opisze całe zlecenie. Firma może dzięki temu ograniczyć zapytania spoza obszaru i lepiej planować trasy między realizacjami.", contactTitle: "Zasięg i termin powinny być częścią pierwszego zgłoszenia.", contactFlow: "Pierwszy kontakt zbiera miejscowość, rodzaj usługi oraz preferowany termin. Jeżeli dojazd jest możliwy, dopiero wtedy dochodzą zdjęcia albo dokładniejszy opis. To pomaga firmie, która pracuje na większym obszarze, ocenić logistykę zanim obieca klientowi konkretną godzinę.", exampleTitle: "Zasięg powiatowy wymaga jasnych zasad dojazdu.", example: "Jeżeli firma obsługuje Wołomin i kilka gmin, warto pokazać ten obszar wprost. Klient powinien przed wysłaniem zapytania wiedzieć, czy jego adres jest w zasięgu i jakie dane będą potrzebne do wyceny.", checklist: ["miasto i obsługiwane gminy", "zasady dojazdu", "czas odpowiedzi na zapytanie", "osobne opisy głównych usług"], related: [["Kobyłka", "kobylka"], ["Zielonka", "zielonka"], ["Radzymin", "radzymin"]] },
  radzymin: { name: "Radzymin", genitive: "Radzymina", locative: "Radzyminie", nearby: "Marki, Wołomin, Nieporęt i północno-wschodnie okolice Warszawy", lead: "Pomagam firmom usługowym stworzyć czytelną ofertę online oraz prostą drogę od lokalnego wyszukiwania do telefonu, formularza i wyceny.", localNeed: "Przy większym obszarze dojazdu klient powinien szybko sprawdzić, czy firma obsługuje jego miejscowość. Formularz może dodatkowo zebrać lokalizację, termin i opis zlecenia.", localContext: "Gdy firma dojeżdża poza sam Radzymin, klient powinien przed rozmową łatwo potwierdzić obszar obsługi. To ogranicza przypadkowe zapytania i skraca wycenę.", fitTitle: "Dla usługodawcy, którego realny rynek jest większy niż samo miasto.", fit: "Przy Radzyminie warto projektować stronę wokół decyzji o dojeździe. Klient nie musi znać wewnętrznych zasad firmy, ale powinien łatwo sprawdzić, czy jego miejscowość jest obsługiwana i co wpływa na termin. To szczególnie ważne przy usługach, w których trasa stanowi istotną część dnia pracy.", contactTitle: "Najpierw lokalizacja i wykonalność, później szczegóły realizacji.", contactFlow: "Formularz może zacząć się od miejsca wykonania usługi i oczekiwanego terminu. Dopiero kolejne pola zbierają zakres oraz materiały pomocnicze. Firma szybciej odrzuca zgłoszenia spoza zasięgu, a klient dostaje jasną odpowiedź, zamiast czekać na telefon tylko po to, by usłyszeć, że dojazd nie jest możliwy.", exampleTitle: "Szeroki dojazd warto zamienić w prostą decyzję klienta.", example: "Zamiast ogólnego hasła „działamy w okolicy” można podać miejscowości, warunki dojazdu i pole na adres. Firma szybciej oceni trasę, a klient od razu wie, czy warto wysłać zgłoszenie.", checklist: ["konkretne miejscowości w zasięgu", "adres w formularzu", "termin realizacji lub oględzin", "informacja o kosztach dojazdu, jeśli występują"], related: [["Wołomin", "wolomin"], ["Kobyłka", "kobylka"], ["Białołęka", "bialoleka"]] },
  targowek: { name: "Targówek", genitive: "Targówka", locative: "Targówku", nearby: "Bródno, Zacisze, Marki, Ząbki i Białołęka", lead: "Tworzę strony i formularze dla usługodawców, którzy konkurują na warszawskim rynku i potrzebują czytelnie pokazać specjalizację, obszar oraz przewagę swojej oferty.", localNeed: "Na Targówku klient ma duży wybór wykonawców. Strona musi w kilka chwil wyjaśnić specjalizację, pokazać wiarygodność i umożliwić wygodny kontakt z telefonu.", localContext: "Na Targówku konkurencja jest duża, dlatego pierwsza część strony powinna od razu łączyć usługę, dowód jakości i prosty kontakt z telefonu.", fitTitle: "Najlepiej działa tam, gdzie klient porównuje kilka firm niemal jednocześnie.", fit: "Na Targówku strona musi szybko pokazać specjalizację, a nie tylko listę wszystkiego, co firma potrafi zrobić. W praktyce oznacza to mocny pierwszy ekran, jednoznaczny obszar działania i dowód jakości blisko głównego CTA. Klient powinien zrozumieć różnicę między ofertami bez otwierania pięciu zakładek.", contactTitle: "Pierwszy ekran ma dać powód do kontaktu, nie tylko numer telefonu.", contactFlow: "Użytkownik najpierw widzi konkretną usługę i przykłady sposobu pracy, a dopiero potem wybiera telefon lub formularz. Dla wykonawcy oznacza to mniej przypadkowych rozmów i większą szansę, że osoba kontaktująca się zna już podstawowy zakres oraz sposób działania firmy.", exampleTitle: "Na telefonie najpierw musi być widać usługę i sposób kontaktu.", example: "Klient z Bródna lub Zacisza często porównuje kilka wyników jeden po drugim. Pierwszy ekran powinien bez przewijania podać specjalizację, obszar pracy i przycisk do telefonu albo konkretnego formularza.", checklist: ["jedna główna specjalizacja na pierwszym ekranie", "Targówek, Bródno i faktyczny zasięg", "widoczny telefon", "dowód pracy: zdjęcie, proces albo prawdziwa opinia"], related: [["Białołęka", "bialoleka"], ["Warszawa", "warszawa"], ["Ząbki", "zabki"]] },
  bialoleka: { name: "Białołęka", genitive: "Białołęki", locative: "Białołęce", nearby: "Targówek, Marki, Nieporęt i północna Warszawa", lead: "Projektuję strony dla firm usługowych z Białołęki, które chcą jasno podać zasięg dojazdu i otrzymywać zgłoszenia z adresem, opisem oraz zdjęciami.", localNeed: "Na Białołęce liczy się jasny obszar dojazdu, wygodna wersja mobilna i możliwość szybkiego przekazania szczegółów. Dobrze ułożona strona skraca drogę do rozmowy.", localContext: "Przy rozproszonych adresach Białołęki dobra strona prowadzi klienta od usługi do przekazania lokalizacji. Dzięki temu firma dostaje informacje potrzebne do oceny dojazdu.", fitTitle: "Dobre rozwiązanie dla usług, w których adres wpływa na logistykę i termin.", fit: "Na Białołęce warto potraktować lokalizację jako praktyczny element zgłoszenia, a nie informację zbieraną na końcu rozmowy. Przy usługach wyjazdowych dokładny adres, część dzielnicy i dostępność czasowa mogą decydować o tym, czy realizacja pasuje do planu dnia.", contactTitle: "Adres pomaga zaplanować pracę zanim firma oddzwoni.", contactFlow: "Klient podaje lokalizację razem z opisem i terminem. Firma może zestawić zgłoszenie z innymi realizacjami w danym dniu i szybciej zaproponować sensowne okno czasowe. To prostsze niż ustalanie trasy dopiero po kilku wiadomościach lub po przyjęciu zlecenia bez sprawdzenia dojazdu.", exampleTitle: "Adres z Tarchomina i adres za Kanałem Żerańskim mogą oznaczać inny dojazd.", example: "Przy usługach wyjazdowych warto zebrać pełną lokalizację już w formularzu. Firma może od razu ocenić trasę, a klient nie musi tłumaczyć jej dopiero podczas rozmowy.", checklist: ["dokładny adres lub część dzielnicy", "godziny możliwego dojazdu", "zakres usługi i zdjęcia", "czy firma obsługuje także okolice poza Warszawą"], related: [["Targówek", "targowek"], ["Warszawa", "warszawa"], ["Radzymin", "radzymin"]] },
  warszawa: { name: "Warszawa", genitive: "Warszawy", locative: "Warszawie", nearby: "Targówek, Białołęka, Bródno, Zacisze oraz miejscowości po wschodniej stronie miasta", lead: "Tworzę strony WWW, formularze wyceny i proste systemy obsługi klientów dla warszawskich firm usługowych, które chcą wyróżnić specjalizację i uporządkować zapytania.", localNeed: "Warszawski klient porównuje wiele ofert. Strona powinna szybko odpowiedzieć na trzy pytania: czy rozwiązujesz jego problem, czy działasz w jego rejonie i jak może przekazać dane potrzebne do rozmowy.", localContext: "W Warszawie sama ogólna obietnica nie wystarcza. Strona powinna pokazać specjalizację, obszar działania i sposób przygotowania do wyceny zanim klient wybierze kolejną ofertę.", fitTitle: "Dla firmy, która musi najpierw wyjaśnić specjalizację, a dopiero potem zasięg.", fit: "W Warszawie ogólna strona „robimy wszystko” szybko przegrywa z ofertą, która nazywa konkretny problem klienta. Dlatego pierwszym zadaniem jest pokazanie specjalizacji i typu zleceń, a dopiero drugim — dzielnic i zasad dojazdu. Taki układ pomaga konkurować jakością dopasowania, nie samą obecnością w mieście.", contactTitle: "Dzielnica nie zastępuje kwalifikacji zapytania.", contactFlow: "Formularz powinien zebrać zarówno lokalizację, jak i rodzaj potrzeby. Dzięki temu firma widzi, czy klient pasuje do specjalizacji, jaki może być pierwszy krok i czy konieczne są oględziny. To szczególnie ważne przy dużym rynku, gdzie sama liczba zapytań nie oznacza jeszcze dobrych zleceń.", exampleTitle: "Ogólne „usługi w Warszawie” nie mówi klientowi, czy jesteś dla niego.", example: "Lepsza strona nazywa konkretną usługę, pokazuje obsługiwane dzielnice i wyjaśnia, jak wygląda pierwszy krok. Klient nie musi szukać tych informacji w stopce ani dzwonić tylko po to, by zapytać o zasięg.", checklist: ["główna usługa i typ klienta", "obsługiwane dzielnice", "termin oraz sposób pierwszej wyceny", "krótki, mobilny formularz"], related: [["Targówek", "targowek"], ["Białołęka", "bialoleka"], ["Ząbki", "zabki"]] },
};

const metadataByCity: Record<string, { title: string; description: string }> = {
  zabki: { title: "Strony internetowe Ząbki dla firm usługowych", description: "Strony WWW dla firm z Ząbek: czytelny zasięg dojazdu, formularz ze zdjęciami i prosty kontakt z telefonu." },
  zielonka: { title: "Strony internetowe Zielonka | usługi lokalne", description: "Strony i formularze dla firm z Zielonki. Osobna ścieżka dla pilnego telefonu i większej wyceny." },
  kobylka: { title: "Strony internetowe Kobyłka | wycena", description: "Strony WWW dla firm z Kobyłki z adresem realizacji, zdjęciami i danymi potrzebnymi przed oddzwonieniem." },
  wolomin: { title: "Strony internetowe Wołomin i okolice", description: "Strony dla firm z Wołomina obsługujących miasto i sąsiednie gminy. Zasięg, dojazd i wycena opisane bez niedomówień." },
  radzymin: { title: "Strony internetowe Radzymin | dojazd", description: "Strony WWW dla firm z Radzymina: miejscowości w zasięgu, adres w formularzu i konkretne zasady pierwszej wyceny." },
  targowek: { title: "Strony internetowe Targówek i Bródno", description: "Strony dla firm z Targówka, Bródna i Zacisza. Specjalizacja, dowód pracy i szybki kontakt widoczne na telefonie." },
  bialoleka: { title: "Strony internetowe Białołęka dla firm", description: "Strony WWW dla firm z Białołęki z dokładną lokalizacją, zakresem usługi i wygodnym formularzem mobilnym." },
  warszawa: { title: "Strony internetowe Warszawa dla małych firm", description: "Strony i formularze dla warszawskich firm usługowych. Konkretna specjalizacja, dzielnice i jasny pierwszy krok klienta." },
};

export function generateStaticParams() { return Object.keys(cities).map(miasto => ({ miasto })); }

export async function generateMetadata({ params }: { params: Promise<{ miasto: string }> }): Promise<Metadata> {
  const { miasto } = await params;
  const city = cities[miasto];
  if (!city) return {};
  const title = metadataByCity[miasto].title;
  const description = metadataByCity[miasto].description;
  return { title, description, alternates: { canonical: `/strony-internetowe/${miasto}` }, openGraph: { title: `${title} | Zielona Marka`, description, images: ["/og.jpg"] }, twitter: { card: "summary_large_image", title: `${title} | Zielona Marka`, description, images: ["/og.jpg"] } };
}

export default async function LocalCityRoute({ params }: { params: Promise<{ miasto: string }> }) {
  const { miasto } = await params;
  const city = cities[miasto];
  if (!city) notFound();
  return <LocalCityPage city={city} />;
}
