"use client";
import { useState } from "react";
const services=[{category:"Relaks",name:"Masaż aromatyczny",duration:"60 min",price:190,detail:"Spokojne tempo i delikatny zapach olejków."},{category:"Klasyczne",name:"Masaż klasyczny",duration:"60 min",price:210,detail:"Chwila uważności dla pleców, ramion i całego ciała."},{category:"Relaks",name:"Rytuał ciepłych kamieni",duration:"90 min",price:290,detail:"Otulające ciepło i czas tylko dla siebie."},{category:"Rytuały",name:"Rytuał twarzy",duration:"75 min",price:240,detail:"Pielęgnacja i łagodny masaż w spokojnej atmosferze."}];
export default function MassageServices(){
 const [category,setCategory]=useState("Wszystkie");const [selected,setSelected]=useState("");const [confirmed,setConfirmed]=useState(false);
 return <><div className="ns-filters" aria-label="Rodzaje masażu">{["Wszystkie","Relaks","Klasyczne","Rytuały"].map(c=><button key={c} type="button" aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 <div className="ns-services">{services.filter(s=>category==="Wszystkie"||s.category===category).map((s)=><article key={s.name}><span className="ns-service-symbol" aria-hidden="true">✧</span><small>{s.category}</small><h3>{s.name}</h3><p>{s.detail}</p><div><span>{s.duration}</span><b>{s.price} zł</b></div><button type="button" aria-pressed={selected===s.name} onClick={()=>{setSelected(s.name);setConfirmed(false)}}>{selected===s.name?"Wybrano ✓":"Wybierz rytuał ↗"}</button></article>)}</div>
 <div className="ns-selection" id="rezerwacja"><span className="ns-kicker">TWÓJ CZAS</span><h2>Zacznij od wyboru rytuału.</h2><p>{selected?`Wybrany zabieg: ${selected}.`:"Wybierz jedną z usług powyżej, aby zobaczyć następny krok."}</p>{selected&&<button type="button" onClick={()=>setConfirmed(true)}>Sprawdź przykładową rezerwację ↗</button>}{confirmed&&<p role="status">Tak może wyglądać początek rezerwacji. W tym demo nie zapisujemy wizyty ani danych osobowych.</p>}<small>Projekt poglądowy. Usługi i ceny są przykładowe.</small></div></>;
}
