import type {Metadata} from 'next';
import MassageServices from './MassageServices';
import './massage-demo.css';
export const metadata:Metadata={title:'Natura Studio | masaże i rytuały, demonstracja',description:'Poglądowa strona studia masażu z usługami, cenami i wyborem rytuału.',robots:{index:false,follow:false},openGraph:{images:[]},twitter:{images:[]}};
export default function NaturaSite(){return <main className="ns-site">
 <div className="ns-demo">PROJEKT POGLĄDOWY <a href="/realizacje">Zielona Marka / portfolio ↗</a></div>
 <div className="ns-opening"><nav className="ns-nav" aria-label="Natura Studio"><a href="#start" className="ns-brand">✧ Natura <span>STUDIO MASAŻU</span></a><div><a href="#zabiegi">Masaże</a><a href="#filozofia">O nas</a><a href="#voucher">Vouchery</a></div><a className="ns-button" href="#zabiegi">Wybierz rytuał ↗</a></nav>
 <header id="start" className="ns-hero"><span className="ns-kicker">WARSZAWA · CZAS DLA SIEBIE</span><h1>Odłóż pośpiech.<br/><em>Wróć do siebie.</em></h1><p>Masaże i rytuały w kameralnej przestrzeni.<br/>Daj sobie chwilę, która należy tylko do Ciebie.</p><a className="ns-button" href="#zabiegi">Odkryj swój rytuał</a><a className="ns-scroll" href="#zabiegi">ODDECH. SPOKÓJ. UWAŻNOŚĆ. ↓</a></header></div>
 <section className="ns-offer ns-wrap" id="zabiegi"><header><span className="ns-kicker">UWAŻNY DOTYK</span><h2>Jak chcesz się dziś poczuć?</h2><p>Wybierz spokojniejszy rytm. Zobacz masaże, czas wizyty i przykładowe ceny.</p></header><MassageServices/></section>
 <section className="ns-philosophy ns-wrap" id="filozofia"><figure><img src="/concept-natura.jpg" alt="Naturalne wnętrze koncepcyjnego studia masażu" loading="lazy"/><figcaption>Przestrzeń na spokojniejszą chwilę.</figcaption></figure><div><span className="ns-kicker">NASZA FILOZOFIA</span><h2>Najpierw słuchamy.<br/><em>Potem dobieramy rytuał.</em></h2><p>Liczy się Twój komfort. Spokojna rozmowa, jasny przebieg wizyty i czas, którego nie trzeba dzielić z codziennymi sprawami.</p><ul><li>Indywidualne tempo wizyty</li><li>Kameralna atmosfera</li><li>Czytelny czas i cena zabiegu</li></ul></div></section>
 <section className="ns-voucher" id="voucher"><div><span className="ns-kicker">PODARUJ CHWILĘ</span><h2>Najlepszy prezent?<br/><em>Czas dla siebie.</em></h2><p>Voucher na wybrany rytuał. Piękny gest bez wielkiej okazji.</p><a className="ns-button" href="#zabiegi">Poznaj rytuały ↗</a></div><div className="ns-gift" aria-label="Przykładowy voucher"><span>NATURA STUDIO</span><b>Chwila<br/>dla Ciebie.</b><small>VOUCHER PODARUNKOWY / DEMO</small></div></section>
 <footer className="ns-footer"><div className="ns-brand">✧ Natura <span>STUDIO MASAŻU</span></div><p>Projekt demonstracyjny, fikcyjna marka.<br/>Nie przyjmujemy rzeczywistych rezerwacji.</p><div><a href="/demo/natura">Zobacz przykładowe zaplecze ↗</a><a href="/kontakt">Chcę stronę dla mojego studia ↗</a><a href="/realizacje">Wróć do portfolio</a></div></footer>
 </main>}
