import type { Metadata } from "next";
import Link from "../SafeLink";
import { SiteHeader, SiteFooter } from "../SiteChrome";
import "../home-v5.css";

export const metadata: Metadata = {
  title: "Websites for service businesses in Warsaw",
  description: "Websites, enquiry forms, online shops and CRM for service businesses in Warsaw and Poland. Work directly with Łukasz from scope to launch.",
  alternates: { canonical: "/en", languages: { pl: "/", en: "/en" } },
  openGraph: {
    locale: "en_GB",
    title: "Zielona Marka | Websites and business systems",
    description: "Websites for service businesses, enquiry forms, online shops and CRM. Work directly with Łukasz, from the first conversation to your approval before launch.",
    images: ["/og.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Zielona Marka | Websites and business systems",
    description: "Websites for service businesses, enquiry forms, online shops and CRM. Work directly with Łukasz, from the first conversation to your approval before launch.",
    images: ["/og.jpg"],
  },
};

const chapters = [
  { number: "01 / YOUR WEBSITE", title: "A website that makes your business clear.", copy: "Customers can see what you offer, who you help and how to contact you. I bring content, photographs and navigation together into a clear story about your business.", href: "/oferta", link: "Website scope and prices (PL)", visual: "website" },
  { number: "02 / ENQUIRY FORMS", title: "Less back and forth. More useful details.", copy: "A service, a preferred date and a few words about what is needed. A well-designed form helps a customer explain their request and helps you prepare a conversation or quote.", visual: "form" },
  { number: "03 / SHOP AND PAYMENTS", title: "Your offer reaches beyond a visit.", copy: "A product recommended after a treatment. A gift voucher. Something a customer wants to buy again. I can connect your website to a shop and online payments so customers can also buy from home.", href: "/oferta#mini-sklep", link: "Shop and payment options (PL)", visual: "shop" },
  { number: "04 / CRM AND ORDERS", title: "An enquiry arrives. The next step is clear.", copy: "When agreements have a place, planning your day gets easier. A CRM brings contacts, quotes, dates and order statuses together. You can see who needs a reply and what has already been completed.", href: "/maly-crm-dla-firm", link: "Explore the CRM example (PL)", visual: "crm" },
  { number: "05 / AFTER THE SERVICE", title: "Good relationships deserve care.", copy: "After a service, you may want to check that everything is fine, ask for a review or remind a customer about their next appointment. I help plan that contact and connect it to your order workflow.", visual: "care" },
];
function Illustration({ kind }: { kind: string }) {
  if (kind === "website") return <div className="zmh-visual"><p className="zmh-caption">Wellness website concept · demonstration</p><div className="zmh-website zmh-glass"><div className="zmh-mini-nav"><b>✳ Natura Studio</b><span>About · Services · Contact</span></div><div className="zmh-site-interior"><span>TIME FOR YOURSELF</span><h3>Calmer.<br />Closer to you.</h3><p>Care. Relaxation. Natural beauty.</p><span className="zmh-sample-button">Explore treatments ↗</span></div></div></div>;
  if (kind === "form") return <div className="zmh-visual zmh-form-visual"><div className="zmh-sample-form zmh-glass"><p className="zmh-caption">ILLUSTRATIVE SERVICE FORM</p><h3>Ask about a service</h3><div><span>Service</span><span>Choose a service ⌄</span></div><div><span>Date</span><span>Preferred date ▦</span></div><div><span>Details</span><span>Tell us what you need…</span></div><span className="zmh-sample-button">Send enquiry →</span></div></div>;
  if (kind === "shop") return <div className="zmh-visual"><div className="zmh-commerce zmh-glass"><div className="zmh-voucher"><small>NATURA STUDIO</small><strong>A moment<br />for you.</strong><span>GIFT VOUCHER</span></div><div className="zmh-commerce-copy"><p className="zmh-caption">ILLUSTRATIVE PURCHASE</p><h3>A thoughtful gift.</h3><p>Product → Basket → Payment</p><small>Voucher purchase demonstration.</small></div></div></div>;
  const labels = kind === "crm" ? ["New enquiry", "Quote", "Delivery"] : ["Completed", "Follow-up", "Next step"];
  return <div className="zmh-visual"><div className="zmh-flow zmh-glass">{labels.map((label, i) => <div key={label} className={`zmh-flow-item${i === 0 ? " zmh-active" : ""}`}><span aria-hidden="true">{["✉", "▤", "✓"][i]}</span><b>{label}</b></div>)}</div><p className="zmh-caption zmh-bottom-caption">Illustrative workflow.</p></div>;
}
export default function EnglishPage() {
  return <main className="zm-v5" lang="en"><a className="zmh-skip" href="#services">Skip to content</a><div className="zmh-forest"><SiteHeader english />
    <section className="zmh-hero zmh-wrap"><div className="zmh-hero-copy"><p className="zmh-eyebrow">WEBSITES AND SYSTEMS FOR BUSINESSES</p><h1>You have a good business.<br /><em>Let’s show it at its best.</em></h1><p className="zmh-lead">I design websites for service businesses. I also help organise enquiries, sales and customer service.</p><p className="zmh-service-line">Forms · Shops and payments · CRM systems</p><div className="zmh-actions"><a className="zmh-pill" href="#services">Explore the possibilities ↓</a><a className="zmh-quiet" href="tel:+48450458466">Let’s talk ↗</a></div><p className="zmh-trust-note">You work directly with me from the first conversation.<br />You review and approve your website before it goes live.</p></div><div className="zmh-hero-foot"><span className="zmh-aside-note">YOUR IDEA.<br />A SHARED DIRECTION.</span><p>Room for<br />your ideas<br />to grow.</p></div></section>
    <div id="services">{chapters.map(chapter => <section className="zmh-story" key={chapter.number}><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">{chapter.number}</p><h2>{chapter.title}</h2><p>{chapter.copy}</p>{chapter.href && <Link className="zmh-text-link" href={chapter.href}>{chapter.link} ↗</Link>}</div><Illustration kind={chapter.visual} /></div></section>)}</div></div>
    <div className="zmh-lower-forest"><section className="zmh-portfolio zmh-wrap" id="projects"><div className="zmh-section-heading"><div><p className="zmh-eyebrow">DEMONSTRATION PROJECTS</p><h2>Explore before you decide.</h2></div><Link className="zmh-pill zmh-outline" href="/realizacje">All projects (PL) ↗</Link></div><p className="zmh-intro">See how a website helps someone choose a service, plan a visit or find a home. Each example responds to a different need.</p><div className="zmh-projects">{[["Natura Studio", "Wellness and beauty", "natura", "Treatments, prices and a clear path to booking."], ["Bistro Forma", "Hospitality", "bistro", "A restaurant’s atmosphere, menu and reservation information."]].map(([name, sector, slug, copy]) => <Link className="zmh-project zmh-glass" href={`/demo/${slug}-strona`} key={slug}><img src={`/concept-${slug}.jpg`} width="600" height="400" loading="lazy" alt={`${name} demonstration interior`} /><div><small>DEMONSTRATION / {sector.toUpperCase()}</small><h3>{name}</h3><p>{copy}</p><span>Explore the demo (PL) ↗</span></div></Link>)}</div><div className="zmh-more-projects"><Link href="/demo/dom-strona">Dom Dobry / homes and availability (PL) ↗</Link><Link href="/demo/transport">TransportFlow / operations dashboard (PL) ↗</Link></div><p className="zmh-caption">Independent demonstrations of possible solutions. These are not client commissions.</p></section>
    <section className="zmh-process zmh-wrap" id="process"><p className="zmh-chapter">WORKING WITH ZIELONA MARKA</p><h2>A calm process.<br />A shared direction.</h2><p>My name is Łukasz. We start with a conversation about your business and what you want to make easier. I propose a solution and scope, so you know what we are preparing and what you will approve.</p><figure className="zmh-founder-photo"><img src="/lukasz-zielona-marka-strona-glowna-20260908.webp" width="1000" height="563" loading="lazy" alt="Łukasz discussing a website project" /><figcaption>You work directly with me, from the idea to your finished website.</figcaption></figure><ol className="zmh-care-steps">{[["Agree the scope", "We choose the features you need and agree the scope before work starts."], ["Prepare the project", "I bring together content, design and tools. You review the complete proposal."], ["Approve the result", "I check how the website works. It goes live after your approval."]].map(([title, copy], i) => <li key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></section>
    <section className="zmh-story zmh-grow"><div className="zmh-wrap zmh-split"><div className="zmh-copy"><p className="zmh-chapter">AFTER LAUNCH / WEBSITE CARE</p><h2>Grow at your business’s pace.</h2><p>A new service, a sales idea or an easier way to help customers. Your website can grow when the need arises. Ongoing care and new features are agreed separately, to suit your business.</p></div><div className="zmh-growth-words"><span>Care</span><span>Improvements</span><span>Growth</span></div></div></section>
    <section className="zmh-contact zmh-wrap" id="contact"><div><p className="zmh-eyebrow">LET’S START WITH A CONVERSATION</p><h2>Make room<br />for <em>a good change.</em></h2><p>Tell me what your company does and what you would like to make easier for yourself or your customers. A few sentences are enough to start. I will help you choose a direction.</p><a className="zmh-pill" href="mailto:kontakt@zielona-marka.pl?subject=Website%20enquiry">Write about your project ↗</a><a className="zmh-phone" href="tel:+48450458466">+48 450 458 466</a></div></section><SiteFooter english /></div></main>;
}
