"use client";
import type { AnchorHTMLAttributes } from "react";
import { useMemo, useState } from "react";
import { SiteFooter } from "../../SiteChrome";

const Link = ({ href, ...props }: AnchorHTMLAttributes<HTMLAnchorElement>) => <a href={href} {...props} />;

const stages = ["Nowe", "Wycena", "Przypisane", "W trasie", "Dostarczone", "Faktura"];
const initial = [
  { id:"ZT-1048", route:"Poznań → Berlin", client:"Nord-Bud", status:4, value:4800, onTime:true },
  { id:"ZT-1049", route:"Wrocław → Praga", client:"Forma Meble", status:3, value:3600, onTime:true },
  { id:"ZT-1050", route:"Łódź → Gdańsk", client:"Dobry Dom", status:2, value:2850, onTime:true },
  { id:"ZT-1051", route:"Katowice → Brno", client:"Natura Lab", status:1, value:4200, onTime:false },
];

export default function TransportDemo(){
  const [orders,setOrders]=useState(initial); const [log,setLog]=useState(["08:42 · Dokument dostawy ZT-1048 zapisany", "08:35 · Klient otrzymał wiadomość o dostawie", "08:10 · Kierowca potwierdził rozpoczęcie trasy"]);
  const kpi=useMemo(()=>({active:orders.filter(x=>x.status<4).length,revenue:orders.reduce((s,x)=>s+x.value,0),onTime:Math.round(orders.filter(x=>x.onTime).length/orders.length*100),documents:orders.filter(x=>x.status>=4).length}),[orders]);
  function advance(id:string){setOrders(rows=>rows.map(x=>x.id===id?{...x,status:Math.min(5,x.status+1)}:x));const item=orders.find(x=>x.id===id);if(item)setLog(rows=>[`${new Date().toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit"})} · ${id}: ${stages[Math.min(5,item.status+1)]}. Klient i zespół otrzymali aktualizację`,...rows].slice(0,6))}
  function addOrder(){const id=`ZT-${1052+orders.length}`;setOrders(rows=>[...rows,{id,route:"Warszawa → Kraków",client:"Nowe zapytanie",status:0,value:3200,onTime:true}]);setLog(rows=>[`${new Date().toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit"})} · ${id}: formularz utworzył zlecenie i zadanie wyceny`,...rows].slice(0,6))}
  return <><main className="transport-demo zm-backoffice">
    <nav className="demo-simple-nav" aria-label="Powrót do serwisu"><a href="/">← Wróć do strony głównej</a><a href="/kontakt">Zapytaj o wdrożenie ↗</a></nav><div className="zm-demo-bar"><span className="demo-badge">INTERAKTYWNE DEMO · DANE PRZYKŁADOWE</span><div className="demo-return-links"><a href="/demo/routeflow/index.html">Strona firmy transportowej ↗</a></div></div>
    <div className="transport-shell"><section className="transport-title"><div><span className="section-no">ZIELONY TRANSPORT / CENTRUM OPERACYJNE</span><h1>Dzień dobry, zespole.</h1><p>Jeden widok zleceń, terminów, dokumentów i automatyzacji.</p></div><button onClick={addOrder}>+ Zasymuluj nowe zlecenie</button></section>
    <section className="transport-kpis"><article><span>Aktywne zlecenia</span><b>{kpi.active}</b><small>aktualizowane automatycznie</small></article><article><span>Wartość zleceń</span><b>{kpi.revenue.toLocaleString("pl-PL")} zł</b><small>bieżący zestaw demonstracyjny</small></article><article><span>Terminowość</span><b>{kpi.onTime}%</b><small>cel: minimum 95%</small></article><article><span>Dokumenty dostawy</span><b>{kpi.documents}/{orders.length}</b><small>gotowe do rozliczenia</small></article></section>
    <section className="transport-grid"><div className="transport-card work-card"><div className="transport-head"><div><span className="section-no">BIEŻĄCA PRACA</span><h2>Zlecenia w toku</h2></div><small>Kliknij „następny etap”</small></div><div className="work-list">{orders.map(order=><article className="order-row" key={order.id}><div><b>{order.id}</b><small>{order.client}</small></div><div><strong>{order.route}</strong><small>{order.value.toLocaleString("pl-PL")} zł</small></div><span className={`order-status s${order.status}`}>{stages[order.status]}</span><div className="order-progress"><i style={{width:`${(order.status+1)/6*100}%`}}/></div><button disabled={order.status===5} onClick={()=>advance(order.id)}>{order.status===5?"Zakończone":"Następny etap →"}</button></article>)}</div></div>
    <aside className="transport-card automation-card"><div className="transport-head"><div><span className="section-no">AUTOMATYZACJE</span><h2>Co system robi po zmianie statusu</h2></div><small>Od sygnału do wyniku</small></div><div className="automation-flow" aria-label="Schemat działania automatyzacji"><article><span>01 / SYGNAŁ</span><strong>Nowe zlecenie albo kolejny etap trasy</strong></article><article><span>02 / DZIAŁANIE</span><strong>Zadanie dla zespołu, informacja dla klienta i kontrola dokumentów</strong></article><article><span>03 / EFEKT</span><strong>Aktualne ETA, komplet danych i KPI</strong></article></div><h3 className="automation-log-title">Ostatnie działania systemu</h3><div className="automation-log">{log.map((item,index)=><p key={`${item}-${index}`}><i/> {item}</p>)}</div><div className="automation-note"><b>Przykładowy efekt</b><span>Jedna zmiana statusu może uruchomić wiadomość do klienta, zadanie dla pracownika i aktualizację KPI. Wartości w demo są ilustracyjne.</span></div></aside></section>
    <section className="process-blueprint"><header><div><span className="section-no">MAPA PROCESU · 6 ETAPÓW</span><h2>Od zlecenia do rozliczonego transportu.</h2></div><p>Każdy etap pokazuje odpowiedzialność zespołu, działanie automatu i informację, która trafia dalej.</p></header><ol className="process-track transport-process-track">{stages.map((stage,index)=><li key={stage}><small className="process-owner">{index===0?"KLIENT":index===1?"PLANISTA":index===2?"KIEROWCA":index===3?"DOKUMENTY":index===4?"KSIĘGOWOŚĆ":"KPI"}</small><b>{String(index+1).padStart(2,"0")}</b><div><strong>{stage}</strong><span>{["formularz tworzy zlecenie","pojazd i kierowca otrzymują zadanie","status i ETA trafiają do klienta","system pilnuje potwierdzenia dostawy","dane przechodzą do faktury","wynik zasila raport"][index]}</span></div></li>)}</ol><div className="process-result"><span>WYNIK PROCESU</span><strong>Transport rozliczony</strong><small>Klient, operacja i księgowość pracują na tych samych danych.</small></div></section>
    <section className="client-preview"><div><span className="section-no">WIDOK KLIENTA</span><h2>Klient też wie, co się dzieje.</h2><p>Po wpisaniu indywidualnego kodu widzi etap, termin, następny krok oraz umowę bez dostępu do danych innych klientów.</p></div><div className="phone-preview"><small>ZLECENIE ZT-1049</small><b>Transport jest w trasie</b><div><i style={{width:"68%"}}/></div><span>Następny krok: potwierdzenie dostawy</span><button>Umowa i dokumenty ↓</button></div></section></div>
  </main><SiteFooter /></>;
}
