import type { Metadata } from "next";
import Link from "next/link";
import BrandSignature from "../../BrandSignature";
import "./detailflow.css";

export const metadata: Metadata = { title: "DetailFlow: system dla studia detailingu", description: "Demonstracja systemu CRM i zarządzania zleceniami dla studia auto detailingu.", openGraph: { title: "DetailFlow: system dla studia detailingu", description: "Od zapytania do odbioru auta, dokumentów i kolejnej wizyty.", images: [] } };

const stages = [["01","Zapytanie i kwalifikacja","Klient opisuje auto, zakres i termin. Zespół od razu widzi, o co zapytać przed wyceną."],["02","Wycena i rezerwacja","Pakiet, dodatki, czas pracy, zaliczka i zgoda klienta są w jednym zleceniu."],["03","Przyjęcie auta","Protokół stanu, zdjęcia, przebieg i przekazane kluczyki chronią obie strony."],["04","Realizacja i kontrola","Technik pracuje na checkliście. Kierownik widzi stanowisko, etap i rzeczywisty czas."],["05","Odbiór i relacja","Gotowe zdjęcia, zalecenia pielęgnacji, dokument sprzedaży i przypomnienie o następnej usłudze."]];
const modules = [["Klient, auto i historia","Jedna karta łączy kontakt, pojazdy, wcześniejsze usługi, preferencje, zdjęcia oraz historię rozmów."],["Wycena, pakiety i zaliczki","Oferta powstaje z zakresu, dodatków i czasu pracy. Status zaliczki i zgody nie ginie w wiadomościach."],["Kalendarz stanowisk","Planowanie bierze pod uwagę czas usługi, dostępność ludzi i stanowisk. Mniej nakładających się terminów."],["Protokół przyjęcia","Stan auta, przebieg, wyposażenie, rysy, uszkodzenia i zdjęcia są przypisane do zlecenia."],["Checklista jakości","Każdy pakiet ma własną listę kroków. Odbiór następuje dopiero po zakończeniu kontroli."],["Dokumenty i płatności","Zgody, kosztorysy, faktury, potwierdzenia odbioru i terminy płatności pozostają w jednym obiegu."]];

export default function DetailFlowPage(){return <main className="detailflow-page">
  <nav className="detailflow-nav"><Link href="/" className="detailflow-brand"><BrandSignature /></Link><Link href="/?widok=realizacje#realizacje">← Wszystkie realizacje</Link></nav>
  <header className="detailflow-hero"><div><p>REALIZACJA KONCEPCYJNA · AUTO DETAILING</p><h1>Detail<span>Flow</span></h1><h2>Studio pracuje na autach.<br/>System pilnuje reszty.</h2><p className="detailflow-lead">Jedno miejsce dla zapytań, rezerwacji, kart pojazdów, zdjęć, checklist, płatności i opieki po odbiorze. Zaprojektowane pod codzienność studia detailingu, nie pod ogólny arkusz.</p><div className="detailflow-actions"><a href="#system">Zobacz system <b>↓</b></a><Link href="/#kontakt">Porozmawiajmy o wdrożeniu <b>↗</b></Link></div></div><section className="detailflow-dashboard" aria-label="Przykładowy pulpit DetailFlow"><header><span>DETAILFLOW / DZISIAJ</span><b>08:30 · piątek</b></header><div className="detailflow-metrics"><article><small>OBŁOŻENIE</small><strong>82%</strong><i>+ 9% / tydz.</i></article><article><small>W TOKU</small><strong>06</strong><i>zleceń</i></article><article><small>ODBIORY</small><strong>03</strong><i>dzisiaj</i></article></div><div className="detailflow-job"><span></span><div><small>STANOWISKO 02 · REALIZACJA</small><b>BMW M4 Competition</b><p>korekta lakieru · powłoka ceramiczna</p></div><strong>14:30</strong></div><div className="detailflow-job"><span className="warm"></span><div><small>STANOWISKO 01 · PRZYJĘCIE</small><b>Volvo XC60</b><p>pakiet wnętrza · zabezpieczenie skóry</p></div><strong>10:00</strong></div><footer>Kontrola jakości: 4 z 6 etapów <i><b/></i></footer></section></header>
  <section className="detailflow-problem"><div><p>CO ZMIENIAMY</p><h2>Klient pyta o termin. Zespół szuka zdjęć. Właściciel liczy, czy dzień się spiął.</h2></div><p>To nie są osobne problemy. To jeden proces, który przestał mieć wspólny widok. DetailFlow zbiera go w całość, od pierwszego kontaktu aż po kolejną wizytę.</p></section>
  <section id="system" className="detailflow-system"><header><p>SYSTEM DOPASOWANY DO BRANŻY</p><h2>Nie kolejny CRM.<br/><em>Porządek na stanowisku i w firmie.</em></h2></header><div className="detailflow-modules">{modules.map(([title,text],i)=><article key={title}><b>{String(i+1).padStart(2,"0")}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="detailflow-flow"><header><p>OBIEG ZLECENIA</p><h2>Od pierwszego zdjęcia<br/>do efektu, który klient chce pokazać.</h2></header><div>{stages.map(([number,title,text])=><article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="detailflow-roles"><div><p>KAŻDY WIDZI SWÓJ ZAKRES</p><h2>Jedna firma.<br/><em>Różne widoki.</em></h2><p>Właściciel śledzi wyniki, recepcja prowadzi klienta, detailer realizuje checklistę, a klient widzi status i gotowe materiały. Role ograniczają dostęp, ale nie rozrywają procesu na kilka narzędzi.</p><p className="detailflow-role-pwa">Do strony studia można podpiąć instalowaną aplikację PWA. Działa na telefonie jak aplikacja, a każdy użytkownik dostaje własny widok i uprawnienia.</p><Link className="text-link" href="/realizacje/transportflow#jak-powstal">Zobacz przykład podziału na role i PWA <span>↗</span></Link></div><div>{[["Właściciel","obrót, marża, obłożenie stanowisk, terminy płatności i obraz firmy bez czekania na raport"],["Recepcja","zapytania, wyceny, kalendarz, zaliczki, zgody i jeden widok całego dnia"],["Detailer","plan pracy, karta auta, checklisty, zdjęcia przed i po oraz wykonane etapy"],["Klient","potwierdzenie terminu, status zlecenia, zdjęcia efektu, zalecenia i historia usług"]].map(([role,text],i)=><article key={role}><b>{String(i+1).padStart(2,"0")}</b><h3>{role}</h3><p>{text}</p></article>)}</div></section>
  <section className="detailflow-quality"><div><p>JAKOŚĆ, KTÓRĄ MOŻNA UDOWODNIĆ</p><h2>Zdjęcia przed i po nie są dodatkiem. Są częścią zlecenia.</h2><p>Telefon detailera wystarcza, aby dołączyć zdjęcie elementu, oznaczyć etap i przekazać gotowy efekt do odbioru. Klient dostaje profesjonalne podsumowanie zamiast luźnego zestawu plików.</p></div><div className="detailflow-qa-card"><header><span>KARTA KONTROLI · BMW M4</span><b>GOTOWE 6/6</b></header>{["Dokumentacja przyjęcia auta","Korekta lakieru","Aplikacja powłoki","Kontrola detali i szyb","Zdjęcia efektu","Zalecenia dla klienta"].map((item,i)=><p key={item}><b>✓</b><span>{item}</span><small>{i===5?"wysłano":"zatwierdzone"}</small></p>)}<footer>Odbiór: dzisiaj, 14:30</footer></div></section>
  <section className="detailflow-kpi"><header><p>WŁAŚCICIEL WIDZI TO, CO WAŻNE</p><h2>KPI bez układania raportu na koniec miesiąca.</h2></header><div>{[["Obłożenie","ile czasu stanowiska pracują realnie"],["Marża na usłudze","co zostaje po materiale i czasie pracy"],["Średni koszyk","które pakiety i dodatki budują sprzedaż"],["Powroty klientów","kto jest gotowy na kolejną usługę"],["Terminowość","czy odbiory dzieją się zgodnie z planem"],["Płatności","zaliczki, rozliczenia i terminy po odbiorze"]].map(([title,text])=><article key={title}><strong>{title}</strong><span>{text}</span></article>)}</div></section>
  <section className="detailflow-cta"><p>DETAILFLOW · DEMONSTRACJA PROCESOWA</p><h2>Studio nie musi rosnąć przez dokładanie chaosu.</h2><p>Wdrożenie zaczyna się od mapy procesu, wybranych pakietów usług i rzeczywistych zasad pracy Twojego zespołu.</p><Link href="/#kontakt">Chcę uporządkować studio <b>↗</b></Link></section>
</main>}
