import type { Metadata } from "next";
import Link from "../../SafeLink";
import { SiteFooter, SiteHeader } from "../../SiteChrome";

export const metadata: Metadata = {
  title: "TransportFlow: TMS i CRM dla transportu",
  description: "Demonstracyjny system dla firmy transportowej: zlecenia, flota, kierowcy, dokumenty, KPI, terminy płatności i PWA.",
  alternates: { canonical: "/realizacje/transportflow" },
};

const modules = [
  ["01", "Zlecenia i realizacja", "Trasa, pojazd, kierowca, etap, ETA, koszt oraz marża w jednym rejestrze."],
  ["02", "Flota i kierowcy", "50 zestawów, dostępność, serwis, spalanie, dokumenty, czas pracy i indywidualne karty 58 kierowców."],
  ["03", "Dokumenty", "Obieg od zapytania do faktury, CMR, POD, zdjęcia po dostawie, terminy, wersje i blokady procesu."],
  ["04", "CRM klientów", "Relacje, oferty, limity kredytowe, historia współpracy i osobny widok dla klienta."],
  ["05", "Finanse i płatności", "Marża, należności, warunki handlowe, terminy zapłaty oraz sprawy wymagające kontaktu."],
  ["06", "KPI zarządcze", "Przychód, wykorzystanie floty, puste kilometry, ryzyko dokumentowe i bieżące decyzje."],
];

export default function TransportFlowCaseStudy() {
  return <><SiteHeader /><main>
    <section className="page-hero shell"><span className="eyebrow"><i />REALIZACJA DLA TRANSPORTU</span><h1>Transport nie musi być prowadzony między telefonem, arkuszem i dokumentami.</h1><p>TransportFlow to demonstracyjny TMS i CRM dla firmy zarządzającej flotą około 50 zestawów ciężarowych. Łączy codzienną dyspozycję, kierowców, klientów, dokumenty i pieniądze w jednym spójnym obiegu.</p><div className="hero-actions"><a className="button" href="https://transportflow.zielona-marka.pl" target="_blank" rel="noreferrer">Zobacz demonstrację <span>↗</span></a><a className="text-link" href="#jak-powstal">Jak powstał system <span>↓</span></a></div><p className="legal-note">Wszystkie dane w demonstracji są syntetyczne. System pokazuje sposób organizacji pracy, nie dane prawdziwej firmy.</p></section>

    <section className="section dark-section"><div className="shell operations-grid"><div><span className="section-no">PUNKT WYJŚCIA</span><h2>Najwięcej czasu nie znika na trasie. Znika pomiędzy ludźmi i rozproszonymi informacjami.</h2></div><div><p>Jedna osoba ma zlecenie, druga dokument, kierowca wysyła zdjęcie, klient pyta o termin, a księgowość czeka na komplet do rozliczenia. Gdy te elementy nie są połączone, firma pracuje wolniej i dowiaduje się o problemie zbyt późno.</p><p>Dlatego celem nie był kolejny ekran z tabelą. Celem było narzędzie, które skraca obieg informacji i pozwala szybciej podejmować decyzje.</p></div></div></section>

    <section className="section shell"><div className="section-head"><div><span className="section-no">CO PORZĄDKUJE SYSTEM</span><h2>Jeden proces, sześć najważniejszych obszarów.</h2></div><p>Każdy moduł ma odpowiadać na konkretne pytanie operacyjne, a nie tylko zbierać dane dla samego zbierania.</p></div><div className="crm-module-grid">{modules.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

    <section className="section operations-section"><div className="shell operations-grid"><div><span className="section-no">DOKUMENTY BEZ SZUKANIA</span><h2>Po dostawie kierowca potwierdza wykonanie cyfrowo albo dołącza zdjęcie czy PDF.</h2></div><div><p>Dokument jest przypisany do firmy, pojazdu, kierowcy albo konkretnego zlecenia. Ma status, termin, wersję i regułę blokady. Jeżeli brakuje dokumentu potrzebnego do załadunku, system pokazuje to przed rozpoczęciem pracy.</p><p>To skraca drogę od samochodu do biura i przyspiesza przekazanie kompletu do rozliczenia.</p></div></div></section>

    <section className="section shell"><div className="section-head"><div><span className="section-no">KPI I PIENIĄDZE</span><h2>Właściciel widzi nie tylko wynik. Widzi, gdzie trzeba zareagować.</h2></div><p>Pulpit KPI prowadzi od liczby do źródłowego rejestru. Nie kończy się na kolorowym wykresie.</p></div><div className="problem-grid"><article><span>01</span><h3>Rentowność</h3><p>Przychód, koszt i marża aktywnych zleceń pozwalają szybko ocenić wynik operacyjny.</p></article><article><span>02</span><h3>Flota</h3><p>Wykorzystanie zestawów, serwis i puste kilometry pokazują, gdzie ucieka czas albo pieniądze.</p></article><article><span>03</span><h3>Należności</h3><p>Warunki płatności, pozycje po terminie i wykorzystanie limitu klienta tworzą kolejkę do działania.</p></article><article><span>04</span><h3>Ryzyko</h3><p>Blokady dokumentowe i sprawy pilne pomagają reagować zanim wpłyną na trasę lub rozliczenie.</p></article></div></section>

    <section className="section crm-mobile"><div className="shell crm-mobile-grid"><div><span className="section-no">MOBILNIE I WEDŁUG ROLI</span><h2>Kierowca, klient i biuro widzą <em>to, co jest im potrzebne.</em></h2><p>Kierowca ma własne zadania oraz dokumenty na telefonie. Klient widzi wyłącznie własne przewozy, etap realizacji i dokumenty swojej firmy. Zespół biurowy pracuje na operacjach, finansach, flocie albo relacjach.</p><small>System jest przygotowany jako PWA, więc można dodać go do ekranu telefonu lub tabletu jak aplikację.</small></div><div className="crm-phone" aria-label="Przykładowy widok mobilny TransportFlow"><header><b>TRANSPORTFLOW / DZISIAJ</b><span>9:41</span></header><strong>Moja trasa</strong><article><i />Załadunek potwierdzony</article><article><i />Dokument dostawy do przekazania</article><article><i />Następny etap: rozliczenie</article><footer>Własne zlecenia i dokumenty pod ręką</footer></div></div></section>

    <section className="section shell" id="jak-powstal"><div className="section-head"><div><span className="section-no">JAK POWSTAŁ</span><h2>Zacząłem od procesu firmy, a dopiero potem od technologii.</h2></div><p>To podejście pozwala tworzyć system, który wspiera rzeczywistą pracę zamiast wymuszać pracę pod gotowy szablon.</p></div><div className="industry-outcomes"><div><p>Najpierw rozpisaliśmy pełny cykl zlecenia: zapytanie, oferta, planowanie, załadunek, transport, dostawa, dokumenty, faktura i płatność. Następnie określiłem właściciela każdego etapu, wymagane dane, wyjątki oraz miejsca, w których proces powinien zatrzymać się automatycznie.</p><p>Dopiero na tej podstawie powstały moduły, widoki ról i pulpit zarządczy. Dzięki temu kierowca ma prosty ekran, dyspozytor ma operacje, a właściciel ma wynik i listę decyzji.</p></div><ul><li><b>01</b><span>Model procesu i odpowiedzialności</span></li><li><b>02</b><span>Model danych: zlecenia, pojazdy, kierowcy, klienci i dokumenty</span></li><li><b>03</b><span>Interfejs dla biura, kierowcy i klienta</span></li><li><b>04</b><span>KPI, dokumenty, terminy i kontrola jakości</span></li></ul></div></section>

    <section className="section dark-section"><div className="shell operations-grid"><div><span className="section-no">TECHNOLOGIE</span><h2>Nowoczesna warstwa techniczna, ale zawsze podporządkowana procesowi.</h2></div><div><p>Interfejs zbudowałem w React i TypeScript. Aplikacja korzysta z Vinext oraz Cloudflare Workers. Dane projektowane są dla relacyjnej bazy D1, a pliki dokumentów dla magazynu R2. Modelem danych i migracjami zarządza Drizzle ORM.</p><p>Manifest instalacyjny oraz service worker przygotowują aplikację do działania jako PWA. To fundament pod dalszą rozbudowę, integracje z telematyką, księgowością, paliwem i systemami używanymi przez konkretną firmę.</p><a className="text-link" href="https://github.com/lukaszst-cz/operations-office-portfolio/tree/main/transportflow-control-center" target="_blank" rel="noreferrer">Zobacz dokumentację techniczną <span>↗</span></a></div></div></section>

    <section className="section shell next-project"><span className="section-no">CO TO DAJE FIRMIE</span><h2>Mniej ręcznego przekazywania informacji. Krótsze obiegi. Więcej kontroli.</h2><p>TransportFlow ma dać właścicielowi spokój i kontrolę, dyspozytorowi porządek, kierowcy prostotę, księgowości komplet dokumentów, a klientowi jasny status współpracy.</p><div className="hero-actions"><a className="button" href="https://transportflow.zielona-marka.pl" target="_blank" rel="noreferrer">Otwórz demonstrację <span>↗</span></a><Link className="text-link" href="/kontakt">Porozmawiajmy o wdrożeniu <span>↗</span></Link></div></section>
  </main><SiteFooter /></>;
}
